pub mod builtins;
pub mod control;
pub mod loads;
pub mod ops;
pub mod say;

pub use builtins::*;
pub use control::*;
pub use loads::*;
pub use ops::*;
pub use say::*;

use crate::codegen::target::OperatingSystem;

pub fn emit_header(out: &mut String, os: OperatingSystem) {
    if matches!(os, OperatingSystem::MacOS) {
        out.push_str(".globl _main\n");
        out.push_str(".extern _printf\n");
        out.push_str(".extern _exit\n");
        out.push_str(".extern _atexit\n");
        out.push_str(".extern _getchar\n");
        out.push_str(".extern _fflush\n");
        out.push_str(".extern _calloc\n");
        out.push_str(".extern _malloc\n");
        out.push_str(".extern _free\n");
        out.push_str(".extern _realloc\n");
        out.push_str(".extern _memcpy\n");
        out.push_str(".extern _memset\n");
        out.push_str(".extern _time\n");
        out.push_str(".extern _clock_gettime\n");
        out.push_str(".extern _getenv\n");
        out.push_str(".extern _system\n");
        out.push_str(".extern _usleep\n");
        out.push_str(".extern _mkdir\n");
        out.push_str(".extern _socket\n");
        out.push_str(".extern _connect\n");
        out.push_str(".extern _send\n");
        out.push_str(".extern _recv\n");
        out.push_str(".extern _close\n");
        out.push_str(".extern _bind\n");
        out.push_str(".extern _listen\n");
        out.push_str(".extern _accept\n");
        out.push_str(".extern _htons\n");
        out.push_str(".extern _inet_addr\n");
        out.push_str(".extern _gethostbyname\n");
        out.push_str(".extern _setsockopt\n");
        out.push_str(".extern _getpeername\n");
        out.push_str(".extern _inet_ntoa\n");
        out.push_str(".extern _sendto\n");
        out.push_str(".extern _recvfrom\n");
        out.push_str(".extern _select\n");
        out.push_str(".extern _fcntl\n");
        out.push_str(".extern _sin\n");
        out.push_str(".extern _cos\n");
        out.push_str(".extern _tan\n");
        out.push_str(".extern _asin\n");
        out.push_str(".extern _acos\n");
        out.push_str(".extern _atan\n");
        out.push_str(".extern _atan2\n");
        out.push_str(".extern _sinh\n");
        out.push_str(".extern _cosh\n");
        out.push_str(".extern _tanh\n");
        out.push_str(".extern _log\n");
        out.push_str(".extern _log2\n");
        out.push_str(".extern _log10\n");
        out.push_str(".extern _exp\n");
        out.push_str(".extern _fmod\n");
        out.push_str(".extern _sqrt\n");
        out.push_str(".extern _ceil\n");
        out.push_str(".extern _floor\n");
        out.push_str(".extern _opendir\n");
        out.push_str(".extern _readdir\n");
        out.push_str(".extern _closedir\n");
        out.push_str(".extern _pthread_create\n");
        out.push_str(".extern _pthread_join\n");
        out.push_str(".extern _pthread_self\n");
        out.push_str(".extern _pthread_mutex_init\n");
        out.push_str(".extern _pthread_mutex_lock\n");
        out.push_str(".extern _pthread_mutex_unlock\n");
        out.push_str(".extern _pthread_mutex_destroy\n");
        out.push_str(".extern _getpid\n");
        out.push_str(".extern _getcwd\n");
        out.push_str(".extern _chdir\n");
        out.push_str(".extern _rmdir\n\n");
        out.push_str(".text\n");
        out.push_str("_main:\n");
        out.push_str("    push %rbp\n");
        out.push_str("    mov %rsp, %rbp\n");
        out.push_str("    movq %rdi, alya_argc(%rip)\n");
        out.push_str("    movq %rsi, alya_argv(%rip)\n\n");
    } else {
        out.push_str(".global main\n");
        out.push_str(".extern printf\n");
        out.push_str(".extern exit\n");
        out.push_str(".extern atexit\n");
        out.push_str(".extern getchar\n");
        out.push_str(".extern fflush\n");
        out.push_str(".extern calloc\n");
        out.push_str(".extern malloc\n");
        out.push_str(".extern free\n");
        out.push_str(".extern realloc\n");
        out.push_str(".extern memcpy\n");
        out.push_str(".extern memset\n");
        out.push_str(".extern time\n");
        out.push_str(".extern getenv\n");
        out.push_str(".extern system\n");
        if matches!(os, OperatingSystem::Windows) {
            out.push_str(".extern SetConsoleOutputCP\n");
            out.push_str(".extern SetConsoleCP\n");
            out.push_str(".extern GetConsoleOutputCP\n");
            out.push_str(".extern GetConsoleCP\n");
            out.push_str(".extern GetStdHandle\n");
            out.push_str(".extern GetConsoleMode\n");
            out.push_str(".extern SetConsoleMode\n");
            out.push_str(".extern SetConsoleTitleA\n");
            out.push_str(".extern Beep\n");
            out.push_str(".extern Sleep\n");
            out.push_str(".extern GetTickCount64\n");
            out.push_str(".extern _mkdir\n");
            out.push_str(".extern WSAStartup\n");
            out.push_str(".extern WSACleanup\n");
            out.push_str(".extern socket\n");
            out.push_str(".extern connect\n");
            out.push_str(".extern send\n");
            out.push_str(".extern recv\n");
            out.push_str(".extern closesocket\n");
            out.push_str(".extern bind\n");
            out.push_str(".extern listen\n");
            out.push_str(".extern accept\n");
            out.push_str(".extern htons\n");
            out.push_str(".extern inet_addr\n");
            out.push_str(".extern gethostbyname\n");
            out.push_str(".extern setsockopt\n");
            out.push_str(".extern getpeername\n");
            out.push_str(".extern inet_ntoa\n");
            out.push_str(".extern sendto\n");
            out.push_str(".extern recvfrom\n");
            out.push_str(".extern select\n");
            out.push_str(".extern ioctlsocket\n");
            out.push_str(".extern sin\n");
            out.push_str(".extern cos\n");
            out.push_str(".extern tan\n");
            out.push_str(".extern asin\n");
            out.push_str(".extern acos\n");
            out.push_str(".extern atan\n");
            out.push_str(".extern atan2\n");
            out.push_str(".extern sinh\n");
            out.push_str(".extern cosh\n");
            out.push_str(".extern tanh\n");
            out.push_str(".extern log\n");
            out.push_str(".extern log2\n");
            out.push_str(".extern log10\n");
            out.push_str(".extern exp\n");
            out.push_str(".extern fmod\n");
            out.push_str(".extern sqrt\n");
            out.push_str(".extern ceil\n");
            out.push_str(".extern floor\n");
            out.push_str(".extern FindFirstFileA\n");
            out.push_str(".extern FindNextFileA\n");
            out.push_str(".extern FindClose\n");
            out.push_str(".extern CreateThread\n");
            out.push_str(".extern WaitForSingleObject\n");
            out.push_str(".extern CloseHandle\n");
            out.push_str(".extern GetCurrentThreadId\n");
            out.push_str(".extern CreateMutexA\n");
            out.push_str(".extern ReleaseMutex\n");
            out.push_str(".extern GetCurrentProcessId\n");
            out.push_str(".extern GetCurrentDirectoryA\n");
            out.push_str(".extern SetCurrentDirectoryA\n");
            out.push_str(".extern GetFileAttributesA\n");
            out.push_str(".extern _rmdir\n\n");
        } else {
            out.push_str(".extern usleep\n");
            out.push_str(".extern clock_gettime\n");
            out.push_str(".extern mkdir\n");
            out.push_str(".extern socket\n");
            out.push_str(".extern connect\n");
            out.push_str(".extern send\n");
            out.push_str(".extern recv\n");
            out.push_str(".extern close\n");
            out.push_str(".extern bind\n");
            out.push_str(".extern listen\n");
            out.push_str(".extern accept\n");
            out.push_str(".extern htons\n");
            out.push_str(".extern inet_addr\n");
            out.push_str(".extern gethostbyname\n");
            out.push_str(".extern setsockopt\n");
            out.push_str(".extern getpeername\n");
            out.push_str(".extern inet_ntoa\n");
            out.push_str(".extern sendto\n");
            out.push_str(".extern recvfrom\n");
            out.push_str(".extern select\n");
            out.push_str(".extern fcntl\n");
            out.push_str(".extern sin\n");
            out.push_str(".extern cos\n");
            out.push_str(".extern tan\n");
            out.push_str(".extern asin\n");
            out.push_str(".extern acos\n");
            out.push_str(".extern atan\n");
            out.push_str(".extern atan2\n");
            out.push_str(".extern sinh\n");
            out.push_str(".extern cosh\n");
            out.push_str(".extern tanh\n");
            out.push_str(".extern log\n");
            out.push_str(".extern log2\n");
            out.push_str(".extern log10\n");
            out.push_str(".extern exp\n");
            out.push_str(".extern fmod\n");
            out.push_str(".extern sqrt\n");
            out.push_str(".extern ceil\n");
            out.push_str(".extern floor\n");
            out.push_str(".extern opendir\n");
            out.push_str(".extern readdir\n");
            out.push_str(".extern closedir\n");
            out.push_str(".extern pthread_create\n");
            out.push_str(".extern pthread_join\n");
            out.push_str(".extern pthread_self\n");
            out.push_str(".extern pthread_mutex_init\n");
            out.push_str(".extern pthread_mutex_lock\n");
            out.push_str(".extern pthread_mutex_unlock\n");
            out.push_str(".extern pthread_mutex_destroy\n");
            out.push_str(".extern getpid\n");
            out.push_str(".extern getcwd\n");
            out.push_str(".extern chdir\n");
            out.push_str(".extern rmdir\n\n");
        }
        out.push_str(".text\n");
        out.push_str("main:\n");
        out.push_str("    push %rbp\n");
        out.push_str("    mov %rsp, %rbp\n");
        if matches!(os, OperatingSystem::Windows) {
            out.push_str("    movq %rcx, alya_argc(%rip)\n");
            out.push_str("    movq %rdx, alya_argv(%rip)\n\n");
            out.push_str("    sub $48, %rsp\n");
            out.push_str("    mov $65001, %ecx\n");
            out.push_str("    call SetConsoleOutputCP\n");
            out.push_str("    mov $65001, %ecx\n");
            out.push_str("    call SetConsoleCP\n");
            out.push_str("    mov $-11, %ecx\n");
            out.push_str("    call GetStdHandle\n");
            out.push_str("    mov %rax, %rcx\n");
            out.push_str("    lea 32(%rsp), %rdx\n");
            out.push_str("    call GetConsoleMode\n");
            out.push_str("    mov $-11, %ecx\n");
            out.push_str("    call GetStdHandle\n");
            out.push_str("    mov %rax, %rcx\n");
            out.push_str("    mov 32(%rsp), %edx\n");
            out.push_str("    or $4, %edx\n");
            out.push_str("    call SetConsoleMode\n");
            out.push_str("    mov $0x0202, %ecx\n");
            out.push_str("    lea alya_wsa_data(%rip), %rdx\n");
            out.push_str("    call WSAStartup\n");
            out.push_str("    add $48, %rsp\n\n");
        } else {
            out.push_str("    movq %rdi, alya_argc(%rip)\n");
            out.push_str("    movq %rsi, alya_argv(%rip)\n\n");
        }
    }
}

pub fn emit_footer(out: &mut String) {
    out.push_str("    xor %rax, %rax\n");
    out.push_str("    mov %rbp, %rsp\n");
    out.push_str("    pop %rbp\n");
    out.push_str("    ret\n");
}
