use super::toml::{parse_string_array, strip_toml_comment, unquote};
use super::types::{LockedPackage, PackageLock};

pub fn parse_lockfile(content: &str) -> Result<PackageLock, String> {
    let mut version = 1;
    let mut packages = Vec::new();
    let mut current_pkg: Option<LockedPackage> = None;
    let mut in_dependencies = false;

    for line in content.lines() {
        let trimmed = strip_toml_comment(line);
        if trimmed.is_empty() {
            continue;
        }

        if trimmed == "[[package]]" {
            in_dependencies = false;
            if let Some(pkg) = current_pkg.take() {
                packages.push(pkg);
            }
            current_pkg = Some(LockedPackage {
                name: String::new(),
                version: String::new(),
                source: String::new(),
                entry: String::new(),
                checksum: String::new(),
                dependencies: Vec::new(),
            });
            continue;
        }

        if in_dependencies {
            if trimmed == "]" {
                in_dependencies = false;
                continue;
            }
            if trimmed.ends_with(']') {
                in_dependencies = false;
                let inside = trimmed.trim_end_matches(']').trim().trim_end_matches(',');
                let dep = unquote(inside.trim());
                if !dep.is_empty() {
                    if let Some(ref mut pkg) = current_pkg {
                        pkg.dependencies.push(dep);
                    }
                }
                continue;
            }
            let item = trimmed.trim_end_matches(',');
            let dep = unquote(item.trim());
            if !dep.is_empty() {
                if let Some(ref mut pkg) = current_pkg {
                    pkg.dependencies.push(dep);
                }
            }
            continue;
        }

        if let Some((k, v)) = trimmed.split_once('=') {
            let key = k.trim();
            let raw_val = v.trim();

            if let Some(ref mut pkg) = current_pkg {
                match key {
                    "name" => pkg.name = unquote(raw_val),
                    "version" => pkg.version = unquote(raw_val),
                    "source" => pkg.source = unquote(raw_val),
                    "entry" => pkg.entry = unquote(raw_val),
                    "checksum" => pkg.checksum = unquote(raw_val),
                    "dependencies" if raw_val.starts_with('[') => {
                        if raw_val.ends_with(']') {
                            pkg.dependencies = parse_string_array(raw_val);
                        } else {
                            in_dependencies = true;
                            if let Some(after_bracket) = raw_val.strip_prefix('[') {
                                let after_bracket = after_bracket.trim();
                                if !after_bracket.is_empty() {
                                    let item = after_bracket.trim_end_matches(',');
                                    let dep = unquote(item.trim());
                                    if !dep.is_empty() {
                                        pkg.dependencies.push(dep);
                                    }
                                }
                            }
                        }
                    }
                    _ => {}
                }
            } else if key == "version" {
                version = unquote(raw_val).parse::<u32>().unwrap_or(1);
            }
        }
    }

    if let Some(pkg) = current_pkg {
        packages.push(pkg);
    }

    Ok(PackageLock { version, packages })
}

pub fn serialize_lockfile(lock: &PackageLock) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by Alya Package Manager. DO NOT EDIT.\n");
    out.push_str(&format!("version = {}\n", lock.version));
    for pkg in &lock.packages {
        out.push_str("\n[[package]]\n");
        out.push_str(&format!("name = \"{}\"\n", pkg.name));
        out.push_str(&format!("version = \"{}\"\n", pkg.version));
        out.push_str(&format!("source = \"{}\"\n", pkg.source));
        out.push_str(&format!("entry = \"{}\"\n", pkg.entry.replace('\\', "/")));
        out.push_str(&format!("checksum = \"{}\"\n", pkg.checksum));
        if !pkg.dependencies.is_empty() {
            out.push_str("dependencies = [\n");
            for dep in &pkg.dependencies {
                out.push_str(&format!(" \"{}\",\n", dep));
            }
            out.push_str("]\n");
        }
    }
    out
}

/// Formats a git dependency source URL for `alya.lock`.
///
/// Examples:
/// - branch: `git:<url>?branch=<branch>#<commit_sha>` (or `#<branch>` if sha unavailable)
/// - tag: `git:<url>?tag=<tag>#<commit_sha>` (or `#<tag>` if sha unavailable)
/// - rev / default: `git:<url>#<commit_sha>` (or `#head` if unavailable)
pub fn format_git_source(
    url: &str,
    branch: Option<&str>,
    tag: Option<&str>,
    rev: Option<&str>,
    commit_sha: Option<&str>,
) -> String {
    if let Some(b) = branch {
        if let Some(sha) = commit_sha {
            format!("git:{}?branch={}#{}", url, b, sha)
        } else {
            format!("git:{}#{}", url, b)
        }
    } else if let Some(t) = tag {
        if let Some(sha) = commit_sha {
            format!("git:{}?tag={}#{}", url, t, sha)
        } else {
            format!("git:{}#{}", url, t)
        }
    } else if let Some(r) = rev {
        if let Some(sha) = commit_sha {
            format!("git:{}#{}", url, sha)
        } else {
            format!("git:{}#{}", url, r)
        }
    } else if let Some(sha) = commit_sha {
        format!("git:{}#{}", url, sha)
    } else {
        format!("git:{}#head", url)
    }
}

/// Parses the locked commit SHA from a git source string if present.
///
/// Returns `Some(sha)` if the fragment after '#' is a hex string between 7
/// and 40 characters long (full SHAs and unambiguous short SHAs both count).
/// Anything else (branch/tag names) yields `None`.
pub fn parse_git_source_rev(source: &str) -> Option<String> {
    if !source.starts_with("git:") {
        return None;
    }
    let after_prefix = &source[4..];
    if let Some((_, fragment)) = after_prefix.split_once('#') {
        let trimmed = fragment.trim();
        if (7..=40).contains(&trimmed.len()) && trimmed.chars().all(|c| c.is_ascii_hexdigit()) {
            return Some(trimmed.to_string());
        }
    }
    None
}
