[package]
name = "http_server"
version = "1.0.0"
alya-version = "0.0.18"
entry = "main.alya"
description = "High-performance native multi-threaded HTTP/1.1 web server with MIME auto-detection"
authors = ["Alya Language Contributors <https://github.com/alya-lang>"]
license = "MIT"
homepage = "https://github.com/alya-lang/alya"
repository = "https://github.com/alya-lang/alya"
keywords = ["alya", "alya-lang", "package", "http", "server", "web", "multithreading", "tcp", "network"]

[dependencies]
mime = { git = "https://github.com/alya-lang/mime", branch = "main" }
term = { git = "https://github.com/alya-lang/term", branch = "main" }
