use crate::codegen::target::OperatingSystem;
use super::emit_adrp_add;

#[rustfmt::skip]
pub fn emit(out: &mut String, os: OperatingSystem) {
    let is_win = matches!(os, OperatingSystem::Windows);
    let p = if matches!(os, OperatingSystem::MacOS) { "_" } else { "" };
    let _ = (is_win, p);

    // alya_array_new
    out.push_str(".align 2\n");
    out.push_str("alya_array_new:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x0\n");
    out.push_str("    cmp x20, #8\n");
    out.push_str("    b.ge .L_arm64_new_cap_ok\n");
    out.push_str("    mov x20, #8\n");
    out.push_str("    b .L_arm64_new_alloc\n");
    out.push_str(".L_arm64_new_cap_ok:\n");
    out.push_str("    lsl x20, x20, #1\n");
    out.push_str(".L_arm64_new_alloc:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    mov x1, #40\n");
    out.push_str(&format!("    bl {}calloc\n", p));
    out.push_str("    movz x1, #0x0001\n");
    out.push_str("    movk x1, #0x5A11, lsl #16\n");
    out.push_str("    str x1, [x0]\n");
    out.push_str("    mov x1, #1\n");
    out.push_str("    str x1, [x0, #8]\n");
    out.push_str("    add x21, x0, #16\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    mov x1, #8\n");
    out.push_str(&format!("    bl {}calloc\n", p));
    out.push_str("    str x19, [x21]\n");
    out.push_str("    str x20, [x21, #8]\n");
    out.push_str("    str x0, [x21, #16]\n");
    out.push_str("    lsl x1, x20, #3\n");
    out.push_str("    add x1, x1, #40\n");
    emit_adrp_add(out, "x2", "alya_allocated_bytes", os);
    out.push_str("    ldr x3, [x2]\n");
    out.push_str("    add x3, x3, x1\n");
    out.push_str("    str x3, [x2]\n");
    out.push_str("    mov x0, x21\n");
    out.push_str("    mov x2, #1\n");
    out.push_str("    mov x3, #0\n");
    out.push_str("    stp x0, x1, [sp, #-16]!\n");
    out.push_str("    bl alya_mem_track_alloc\n");
    out.push_str("    ldp x0, x1, [sp], #16\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // alya_array_push
    out.push_str(".align 2\n");
    out.push_str("alya_array_push:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    ldr x21, [x19]\n");
    out.push_str("    ldr x22, [x19, #8]\n");
    out.push_str("    cmp x21, x22\n");
    out.push_str("    b.lt .L_arm64_push_store\n");
    out.push_str("    cbnz x22, .L_arm64_push_double\n");
    out.push_str("    mov x22, #8\n");
    out.push_str("    b .L_arm64_push_realloc\n");
    out.push_str(".L_arm64_push_double:\n");
    out.push_str("    lsl x22, x22, #1\n");
    out.push_str(".L_arm64_push_realloc:\n");
    out.push_str("    str x22, [x19, #8]\n");
    out.push_str("    ldr x0, [x19, #16]\n");
    out.push_str("    lsl x1, x22, #3\n");
    out.push_str(&format!("    bl {}realloc\n", p));
    out.push_str("    str x0, [x19, #16]\n");
    out.push_str("    lsl x1, x22, #3\n");
    emit_adrp_add(out, "x2", "alya_allocated_bytes", os);
    out.push_str("    ldr x3, [x2]\n");
    out.push_str("    add x3, x3, x1\n");
    out.push_str("    str x3, [x2]\n");
    out.push_str(".L_arm64_push_store:\n");
    out.push_str("    ldr x2, [x19, #16]\n");
    out.push_str("    str x20, [x2, x21, lsl #3]\n");
    out.push_str("    add x21, x21, #1\n");
    out.push_str("    str x21, [x19]\n");
    out.push_str("    mov x0, x21\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // alya_array_pop
    out.push_str(".align 2\n");
    out.push_str("alya_array_pop:\n");
    out.push_str("    stp x29, x30, [sp, #-16]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    ldr x1, [x0]\n");
    out.push_str("    cmp x1, #0\n");
    out.push_str("    b.le alya_error_index_out_of_bounds\n");
    out.push_str("    sub x1, x1, #1\n");
    out.push_str("    str x1, [x0]\n");
    out.push_str("    ldr x2, [x0, #16]\n");
    out.push_str("    ldr x0, [x2, x1, lsl #3]\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n\n");

    // alya_print_array
    out.push_str(".align 2\n");
    out.push_str("alya_print_array:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    cbnz x19, .L_arm64_arr_not_null\n");
    emit_adrp_add(out, "x0", "alya_fmt_arr_empty", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str("    b .L_arm64_arr_exit\n");
    out.push_str(".L_arm64_arr_not_null:\n");
    out.push_str("    ldr x20, [x19]\n");
    emit_adrp_add(out, "x0", "alya_fmt_arr_open", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str("    mov x21, #0\n");
    out.push_str(".L_arm64_arr_loop:\n");
    out.push_str("    cmp x21, x20\n");
    out.push_str("    b.ge .L_arm64_arr_close_call\n");
    out.push_str("    cbz x21, .L_arm64_arr_print_elem\n");
    emit_adrp_add(out, "x0", "alya_fmt_arr_comma", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str(".L_arm64_arr_print_elem:\n");
    emit_adrp_add(out, "x0", "alya_fmt_arr_elem", os);
    out.push_str("    ldr x22, [x19, #16]\n");
    out.push_str("    ldr x1, [x22, x21, lsl #3]\n");
    if matches!(os, OperatingSystem::MacOS) {
        out.push_str("    sub sp, sp, #16\n");
        out.push_str("    str x1, [sp]\n");
        out.push_str(&format!("    bl {}printf\n", p));
        out.push_str("    add sp, sp, #16\n");
    } else {
        out.push_str(&format!("    bl {}printf\n", p));
    }
    out.push_str("    add x21, x21, #1\n");
    out.push_str("    b .L_arm64_arr_loop\n");
    out.push_str(".L_arm64_arr_close_call:\n");
    emit_adrp_add(out, "x0", "alya_fmt_arr_close", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str(".L_arm64_arr_exit:\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_args
    out.push_str(".global fn_args\n");
    out.push_str("fn_args:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    emit_adrp_add(out, "x0", "alya_argc", os);
    out.push_str("    ldr x19, [x0]\n");
    out.push_str("    cmp x19, #1\n");
    out.push_str("    b.gt .L_arm64_args_has_items\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    bl alya_array_new\n");
    out.push_str("    b .L_arm64_args_ret\n");
    out.push_str(".L_arm64_args_has_items:\n");
    out.push_str("    sub x19, x19, #1\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    bl alya_array_new\n");
    out.push_str("    mov x20, x0\n");
    emit_adrp_add(out, "x1", "alya_argv", os);
    out.push_str("    ldr x21, [x1]\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_args_loop:\n");
    out.push_str("    cmp x22, x19\n");
    out.push_str("    b.ge .L_arm64_args_done\n");
    out.push_str("    add x2, x22, #1\n");
    out.push_str("    ldr x3, [x21, x2, lsl #3]\n");
    out.push_str("    ldr x4, [x20, #16]\n");
    out.push_str("    str x3, [x4, x22, lsl #3]\n");
    out.push_str("    add x22, x22, #1\n");
    out.push_str("    b .L_arm64_args_loop\n");
    out.push_str(".L_arm64_args_done:\n");
    out.push_str("    mov x0, x20\n");
    out.push_str(".L_arm64_args_ret:\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // alya_array_slice(arr: x0, start: x1, end: x2)
    out.push_str(".align 2\n");
    out.push_str(".global alya_array_slice\n");
    out.push_str("alya_array_slice:\n");
    out.push_str("    stp x29, x30, [sp, #-64]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    stp x23, x24, [sp, #48]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    mov x21, x2\n");
    out.push_str("    cbz x19, .L_arm64_slice_empty\n");
    out.push_str("    ldr x22, [x19]\n");
    out.push_str("    cmp x20, #0\n");
    out.push_str("    b.ge .L_arm64_slice_start_ok\n");
    out.push_str("    mov x20, #0\n");
    out.push_str(".L_arm64_slice_start_ok:\n");
    out.push_str("    cmp x21, #0\n");
    out.push_str("    b.lt .L_arm64_slice_end_cap\n");
    out.push_str("    cmp x21, x22\n");
    out.push_str("    b.le .L_arm64_slice_end_ok\n");
    out.push_str(".L_arm64_slice_end_cap:\n");
    out.push_str("    mov x21, x22\n");
    out.push_str(".L_arm64_slice_end_ok:\n");
    out.push_str("    cmp x20, x21\n");
    out.push_str("    b.ge .L_arm64_slice_empty\n");
    out.push_str("    sub x23, x21, x20\n");
    out.push_str("    mov x0, x23\n");
    out.push_str("    bl alya_array_new\n");
    out.push_str("    ldr x1, [x19, #16]\n");
    out.push_str("    ldr x2, [x0, #16]\n");
    out.push_str("    mov x3, #0\n");
    out.push_str(".L_arm64_slice_copy_loop:\n");
    out.push_str("    cmp x3, x23\n");
    out.push_str("    b.ge .L_arm64_slice_copy_done\n");
    out.push_str("    add x4, x20, x3\n");
    out.push_str("    ldr x5, [x1, x4, lsl #3]\n");
    out.push_str("    str x5, [x2, x3, lsl #3]\n");
    out.push_str("    add x3, x3, #1\n");
    out.push_str("    b .L_arm64_slice_copy_loop\n");
    out.push_str(".L_arm64_slice_copy_done:\n");
    out.push_str("    str x23, [x0]\n");
    out.push_str("    b .L_arm64_slice_done\n");
    out.push_str(".L_arm64_slice_empty:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    bl alya_array_new\n");
    out.push_str(".L_arm64_slice_done:\n");
    out.push_str("    ldp x23, x24, [sp, #48]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #64\n");
    out.push_str("    ret\n\n");

    // fn_slice
    out.push_str(".align 2\n");
    out.push_str(".global fn_slice\n");
    out.push_str("fn_slice:\n");
    out.push_str("    cbz x0, .L_arm64_fn_slice_null\n");
    out.push_str("    sub x3, x0, #16\n");
    out.push_str("    ldr x3, [x3]\n");
    out.push_str("    movz x4, #0x0001\n");
    out.push_str("    movk x4, #0x5A11, lsl #16\n");
    out.push_str("    cmp x3, x4\n");
    out.push_str("    b.eq alya_array_slice\n");
    out.push_str("    cmp x2, #0\n");
    out.push_str("    b.lt .L_arm64_fn_slice_str_call\n");
    out.push_str("    sub x2, x2, x1\n");
    out.push_str("    cmp x2, #0\n");
    out.push_str("    b.ge .L_arm64_fn_slice_str_call\n");
    out.push_str("    mov x2, #0\n");
    out.push_str(".L_arm64_fn_slice_str_call:\n");
    out.push_str("    b fn_substring\n");
    out.push_str(".L_arm64_fn_slice_null:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n\n");
}
