use crate::codegen::target::OperatingSystem;
use super::emit_adrp_add;

#[rustfmt::skip]
pub fn emit(out: &mut String, os: OperatingSystem) {
    let is_win = matches!(os, OperatingSystem::Windows);
    let p = if matches!(os, OperatingSystem::MacOS) { "_" } else { "" };
    let _ = (is_win, p);

    // fn_file_exists
    out.push_str(".align 2\n");
    out.push_str("fn_file_exists:\n");
    out.push_str("    stp x29, x30, [sp, #-32]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    str x19, [sp, #16]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    cbz x19, .L_arm64_fexists_no\n");
    out.push_str("    mov x0, x19\n");
    emit_adrp_add(out, "x1", "alya_str_mode_rb", os);
    out.push_str(&format!("    bl {}fopen\n", p));
    out.push_str("    cbz x0, .L_arm64_fexists_no\n");
    out.push_str(&format!("    bl {}fclose\n", p));
    out.push_str("    mov x0, #1\n");
    out.push_str("    b .L_arm64_fexists_end\n");
    out.push_str(".L_arm64_fexists_no:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str(".L_arm64_fexists_end:\n");
    out.push_str("    ldr x19, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #32\n");
    out.push_str("    ret\n\n");

    // fn_delete_file / fn_remove_file
    out.push_str(".align 2\n");
    out.push_str(".global fn_delete_file\n");
    out.push_str("fn_delete_file:\n");
    out.push_str(".global fn_remove_file\n");
    out.push_str("fn_remove_file:\n");
    out.push_str("    stp x29, x30, [sp, #-32]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    str x19, [sp, #16]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    cbz x19, .L_arm64_fdel_fail\n");
    out.push_str("    mov x0, x19\n");
    out.push_str(&format!("    bl {}remove\n", p));
    out.push_str("    cbnz x0, .L_arm64_fdel_fail\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    b .L_arm64_fdel_end\n");
    out.push_str(".L_arm64_fdel_fail:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str(".L_arm64_fdel_end:\n");
    out.push_str("    ldr x19, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #32\n");
    out.push_str("    ret\n\n");

    // fn_write_file
    out.push_str(".align 2\n");
    out.push_str("fn_write_file:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    cbz x19, .L_arm64_fwrite_fail\n");
    out.push_str("    mov x0, x19\n");
    emit_adrp_add(out, "x1", "alya_str_mode_wb", os);
    out.push_str(&format!("    bl {}fopen\n", p));
    out.push_str("    cbz x0, .L_arm64_fwrite_fail\n");
    out.push_str("    mov x21, x0\n");
    out.push_str("    mov x22, #0\n");
    out.push_str("    cbz x20, .L_arm64_fwrite_write\n");
    out.push_str("    mov x9, x20\n");
    out.push_str(".L_arm64_fwrite_len_loop:\n");
    out.push_str("    ldrb w10, [x9], #1\n");
    out.push_str("    cbz w10, .L_arm64_fwrite_write\n");
    out.push_str("    add x22, x22, #1\n");
    out.push_str("    b .L_arm64_fwrite_len_loop\n");
    out.push_str(".L_arm64_fwrite_write:\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    mov x1, #1\n");
    out.push_str("    mov x2, x22\n");
    out.push_str("    mov x3, x21\n");
    out.push_str(&format!("    bl {}fwrite\n", p));
    out.push_str("    mov x0, x21\n");
    out.push_str(&format!("    bl {}fclose\n", p));
    out.push_str("    mov x0, #1\n");
    out.push_str("    b .L_arm64_fwrite_end\n");
    out.push_str(".L_arm64_fwrite_fail:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str(".L_arm64_fwrite_end:\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_append_file
    out.push_str(".align 2\n");
    out.push_str(".global fn_append_file\n");
    out.push_str("fn_append_file:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    cbz x19, .L_arm64_fapp_fail\n");
    out.push_str("    mov x0, x19\n");
    emit_adrp_add(out, "x1", "alya_str_mode_ab", os);
    out.push_str(&format!("    bl {}fopen\n", p));
    out.push_str("    cbz x0, .L_arm64_fapp_fail\n");
    out.push_str("    mov x21, x0\n");
    out.push_str("    mov x22, #0\n");
    out.push_str("    cbz x20, .L_arm64_fapp_write\n");
    out.push_str("    mov x9, x20\n");
    out.push_str(".L_arm64_fapp_len_loop:\n");
    out.push_str("    ldrb w10, [x9], #1\n");
    out.push_str("    cbz w10, .L_arm64_fapp_write\n");
    out.push_str("    add x22, x22, #1\n");
    out.push_str("    b .L_arm64_fapp_len_loop\n");
    out.push_str(".L_arm64_fapp_write:\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    mov x1, #1\n");
    out.push_str("    mov x2, x22\n");
    out.push_str("    mov x3, x21\n");
    out.push_str(&format!("    bl {}fwrite\n", p));
    out.push_str("    mov x0, x21\n");
    out.push_str(&format!("    bl {}fclose\n", p));
    out.push_str("    mov x0, #1\n");
    out.push_str("    b .L_arm64_fapp_end\n");
    out.push_str(".L_arm64_fapp_fail:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str(".L_arm64_fapp_end:\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_read_file
    out.push_str(".align 2\n");
    out.push_str("fn_read_file:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    emit_adrp_add(out, "x22", "alya_str_empty", os);
    out.push_str("    mov x19, x0\n");
    out.push_str("    cbz x19, .L_arm64_fread_ret\n");
    out.push_str("    mov x0, x19\n");
    emit_adrp_add(out, "x1", "alya_str_mode_rb", os);
    out.push_str(&format!("    bl {}fopen\n", p));
    out.push_str("    cbz x0, .L_arm64_fread_ret\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    mov x1, #0\n");
    out.push_str("    mov x2, #2\n");
    out.push_str(&format!("    bl {}fseek\n", p));
    out.push_str("    mov x0, x19\n");
    out.push_str(&format!("    bl {}ftell\n", p));
    out.push_str("    cmp x0, #0\n");
    out.push_str("    b.lt .L_arm64_fread_close\n");
    out.push_str("    mov x20, x0\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    mov x1, #0\n");
    out.push_str("    mov x2, #0\n");
    out.push_str(&format!("    bl {}fseek\n", p));
    out.push_str("    mov x0, #1\n");
    out.push_str("    add x1, x20, #1\n");
    out.push_str(&format!("    bl {}calloc\n", p));
    out.push_str("    mov x21, x0\n");
    out.push_str("    mov x22, x0\n");
    out.push_str("    mov x0, x21\n");
    out.push_str("    mov x1, #1\n");
    out.push_str("    mov x2, x20\n");
    out.push_str("    mov x3, x19\n");
    out.push_str(&format!("    bl {}fread\n", p));
    out.push_str("    strb wzr, [x21, x20]\n");
    out.push_str(".L_arm64_fread_close:\n");
    out.push_str("    mov x0, x19\n");
    out.push_str(&format!("    bl {}fclose\n", p));
    out.push_str(".L_arm64_fread_ret:\n");
    out.push_str("    mov x0, x22\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_file_size
    out.push_str(".align 2\n");
    out.push_str(".global fn_file_size\n");
    out.push_str("fn_file_size:\n");
    out.push_str("    stp x29, x30, [sp, #-32]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    cbz x19, .L_arm64_fsize_fail\n");
    out.push_str("    mov x0, x19\n");
    emit_adrp_add(out, "x1", "alya_str_mode_rb", os);
    out.push_str(&format!("    bl {}fopen\n", p));
    out.push_str("    cbz x0, .L_arm64_fsize_fail\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    mov x1, #0\n");
    out.push_str("    mov x2, #2\n");
    out.push_str(&format!("    bl {}fseek\n", p));
    out.push_str("    mov x0, x19\n");
    out.push_str(&format!("    bl {}ftell\n", p));
    out.push_str("    mov x20, x0\n");
    out.push_str("    mov x0, x19\n");
    out.push_str(&format!("    bl {}fclose\n", p));
    out.push_str("    mov x0, x20\n");
    out.push_str("    b .L_arm64_fsize_end\n");
    out.push_str(".L_arm64_fsize_fail:\n");
    out.push_str("    mov x0, #-1\n");
    out.push_str(".L_arm64_fsize_end:\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #32\n");
    out.push_str("    ret\n\n");

    // fn_make_dir / fn_mkdir
    out.push_str(".align 2\n");
    out.push_str(".global fn_make_dir\n");
    out.push_str("fn_make_dir:\n");
    out.push_str(".global fn_mkdir\n");
    out.push_str("fn_mkdir:\n");
    out.push_str("    stp x29, x30, [sp, #-16]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    cbz x0, .L_arm64_mkdir_fail\n");
    out.push_str("    mov x1, #511\n");
    out.push_str(&format!("    bl {}mkdir\n", p));
    out.push_str("    cmp x0, #0\n");
    out.push_str("    cset x0, eq\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_mkdir_fail:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n\n");

    // fn_remove_dir / fn_rmdir
    out.push_str(".align 2\n");
    out.push_str(".global fn_remove_dir\n");
    out.push_str("fn_remove_dir:\n");
    out.push_str(".global fn_rmdir\n");
    out.push_str("fn_rmdir:\n");
    out.push_str("    stp x29, x30, [sp, #-16]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    cbz x0, .L_arm64_rmdir_fail\n");
    out.push_str(&format!("    bl {}rmdir\n", p));
    out.push_str("    cmp x0, #0\n");
    out.push_str("    cset x0, eq\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_rmdir_fail:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n\n");

    // fn_is_dir
    out.push_str(".align 2\n");
    out.push_str(".global fn_is_dir\n");
    out.push_str("fn_is_dir:\n");
    out.push_str("    stp x29, x30, [sp, #-16]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    cbz x0, .L_arm64_isdir_no\n");
    out.push_str(&format!("    bl {}opendir\n", p));
    out.push_str("    cbz x0, .L_arm64_isdir_no\n");
    out.push_str(&format!("    bl {}closedir\n", p));
    out.push_str("    mov x0, #1\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_isdir_no:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n\n");

    // fn_list_dir / fn_read_dir
    let is_mac = matches!(os, OperatingSystem::MacOS);
    let d_off = if is_mac { 21 } else { 19 };
    out.push_str(".align 2\n");
    out.push_str(".global fn_list_dir\n");
    out.push_str("fn_list_dir:\n");
    out.push_str(".global fn_read_dir\n");
    out.push_str("fn_read_dir:\n");
    out.push_str("    stp x29, x30, [sp, #-64]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    bl alya_array_new\n");
    out.push_str("    mov x20, x0\n");
    if is_win {
        // Windows: FindFirstFileA/FindNextFileA over "dir\*" with
        // WIN32_FIND_DATAA at [sp, #32] (592 bytes) and the pattern buffer
        // at [sp, #624] (260 bytes). The 896-byte reservation keeps the
        // 32-byte home area below external calls free.
        out.push_str("    sub sp, sp, #896\n");
        out.push_str("    add x1, sp, #624\n");
        out.push_str("    cbz x19, .L_arm64_ld_win_dot\n");
        out.push_str("    ldrb w2, [x19]\n");
        out.push_str("    cbz w2, .L_arm64_ld_win_dot\n");
        out.push_str("    mov x2, x19\n");
        out.push_str("    mov x3, x1\n");
        out.push_str(".L_arm64_ld_win_cp:\n");
        out.push_str("    ldrb w4, [x2], #1\n");
        out.push_str("    cbz w4, .L_arm64_ld_win_cp_done\n");
        out.push_str("    strb w4, [x3], #1\n");
        out.push_str("    b .L_arm64_ld_win_cp\n");
        out.push_str(".L_arm64_ld_win_dot:\n");
        out.push_str("    mov x3, x1\n");
        out.push_str("    mov w4, #46\n");
        out.push_str("    strb w4, [x3], #1\n");
        out.push_str("    b .L_arm64_ld_win_star\n");
        out.push_str(".L_arm64_ld_win_cp_done:\n");
        out.push_str("    ldrb w4, [x3, #-1]\n");
        out.push_str("    cmp w4, #47\n");
        out.push_str("    b.eq .L_arm64_ld_win_star\n");
        out.push_str("    cmp w4, #92\n");
        out.push_str("    b.eq .L_arm64_ld_win_star\n");
        out.push_str("    mov w4, #47\n");
        out.push_str("    strb w4, [x3], #1\n");
        out.push_str(".L_arm64_ld_win_star:\n");
        out.push_str("    mov w4, #42\n");
        out.push_str("    strb w4, [x3], #1\n");
        out.push_str("    strb wzr, [x3]\n");
        out.push_str("    mov x0, x1\n");
        out.push_str("    add x1, sp, #32\n");
        out.push_str("    bl FindFirstFileA\n");
        out.push_str("    cmn x0, #1\n"); // INVALID_HANDLE_VALUE
        out.push_str("    b.eq .L_arm64_ld_win_done\n");
        out.push_str("    mov x21, x0\n");
        out.push_str(".L_arm64_ld_win_loop:\n");
        out.push_str("    add x22, sp, #76\n"); // cFileName = data + 44
        out.push_str("    ldrb w1, [x22]\n");
        out.push_str("    cmp w1, #46\n");
        out.push_str("    b.ne .L_arm64_ld_win_push\n");
        out.push_str("    ldrb w2, [x22, #1]\n");
        out.push_str("    cbz w2, .L_arm64_ld_win_next\n");
        out.push_str("    cmp w2, #46\n");
        out.push_str("    b.ne .L_arm64_ld_win_push\n");
        out.push_str("    ldrb w3, [x22, #2]\n");
        out.push_str("    cbz w3, .L_arm64_ld_win_next\n");
        out.push_str(".L_arm64_ld_win_push:\n");
        out.push_str("    mov x0, x22\n");
        out.push_str("    bl fn_str_clone\n");
        out.push_str("    mov x1, x0\n");
        out.push_str("    mov x0, x20\n");
        out.push_str("    bl alya_array_push\n");
        out.push_str(".L_arm64_ld_win_next:\n");
        out.push_str("    mov x0, x21\n");
        out.push_str("    add x1, sp, #32\n");
        out.push_str("    bl FindNextFileA\n");
        out.push_str("    cbnz w0, .L_arm64_ld_win_loop\n");
        out.push_str("    mov x0, x21\n");
        out.push_str("    bl FindClose\n");
        out.push_str(".L_arm64_ld_win_done:\n");
        out.push_str("    add sp, sp, #896\n");
    } else {
    out.push_str("    cbz x19, .L_arm64_ld_dot\n");
    out.push_str("    ldrb w1, [x19]\n");
    out.push_str("    cbz w1, .L_arm64_ld_dot\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    b .L_arm64_ld_open\n");
    out.push_str(".L_arm64_ld_dot:\n");
    out.push_str("    mov w1, #46\n");
    out.push_str("    strb w1, [sp, #48]\n");
    out.push_str("    strb wzr, [sp, #49]\n");
    out.push_str("    add x0, sp, #48\n");
    out.push_str(".L_arm64_ld_open:\n");
    out.push_str(&format!("    bl {}opendir\n", p));
    out.push_str("    cbz x0, .L_arm64_ld_ret\n");
    out.push_str("    mov x21, x0\n");
    out.push_str(".L_arm64_ld_loop:\n");
    out.push_str("    mov x0, x21\n");
    out.push_str(&format!("    bl {}readdir\n", p));
    out.push_str("    cbz x0, .L_arm64_ld_close\n");
    out.push_str(&format!("    add x22, x0, #{}\n", d_off));
    out.push_str("    ldrb w1, [x22]\n");
    out.push_str("    cmp w1, #46\n");
    out.push_str("    b.ne .L_arm64_ld_push\n");
    out.push_str("    ldrb w2, [x22, #1]\n");
    out.push_str("    cbz w2, .L_arm64_ld_loop\n");
    out.push_str("    cmp w2, #46\n");
    out.push_str("    b.ne .L_arm64_ld_push\n");
    out.push_str("    ldrb w3, [x22, #2]\n");
    out.push_str("    cbz w3, .L_arm64_ld_loop\n");
    out.push_str(".L_arm64_ld_push:\n");
    out.push_str("    mov x0, x22\n");
    out.push_str("    bl fn_str_clone\n");
    out.push_str("    mov x1, x0\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    bl alya_array_push\n");
    out.push_str("    b .L_arm64_ld_loop\n");
    out.push_str(".L_arm64_ld_close:\n");
    out.push_str("    mov x0, x21\n");
    out.push_str(&format!("    bl {}closedir\n", p));
    }
    out.push_str(".L_arm64_ld_ret:\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x29, x30, [sp], #64\n");
    out.push_str("    ret\n\n");

}
