use crate::codegen::target::OperatingSystem;
use super::emit_adrp_add;

#[rustfmt::skip]
pub fn emit(out: &mut String, os: OperatingSystem) {
    let is_win = matches!(os, OperatingSystem::Windows);
    let p = if matches!(os, OperatingSystem::MacOS) { "_" } else { "" };
    let _ = (is_win, p);

    // alya_map_hash
    out.push_str(".align 2\n");
    out.push_str(".global alya_map_hash\n");
    out.push_str("alya_map_hash:\n");
    out.push_str("    cmp x0, #65536\n");
    out.push_str("    b.lo .L_arm64_mhash_int\n");
    out.push_str("    mov x9, x0\n");
    out.push_str("    mov x0, #5381\n");
    out.push_str(".L_arm64_mhash_loop:\n");
    out.push_str("    ldrb w10, [x9], #1\n");
    out.push_str("    cbz w10, .L_arm64_mhash_done\n");
    out.push_str("    lsl x11, x0, #5\n");
    out.push_str("    add x0, x0, x11\n");
    out.push_str("    add x0, x0, x10\n");
    out.push_str("    b .L_arm64_mhash_loop\n");
    out.push_str(".L_arm64_mhash_int:\n");
    out.push_str(".L_arm64_mhash_done:\n");
    out.push_str("    ret\n\n");

    // alya_map_key_eq / fn_streq
    out.push_str(".align 2\n");
    out.push_str(".global fn_streq\n");
    out.push_str("fn_streq:\n");
    out.push_str(".global alya_map_key_eq\n");
    out.push_str("alya_map_key_eq:\n");
    out.push_str("    cmp x0, x1\n");
    out.push_str("    b.eq .L_arm64_mkeq_true\n");
    out.push_str("    cmp x0, #65536\n");
    out.push_str("    b.lo .L_arm64_mkeq_false\n");
    out.push_str("    cmp x1, #65536\n");
    out.push_str("    b.lo .L_arm64_mkeq_false\n");
    out.push_str(".L_arm64_mkeq_str:\n");
    out.push_str("    ldrb w2, [x0], #1\n");
    out.push_str("    ldrb w3, [x1], #1\n");
    out.push_str("    cmp w2, w3\n");
    out.push_str("    b.ne .L_arm64_mkeq_false\n");
    out.push_str("    cbz w2, .L_arm64_mkeq_true\n");
    out.push_str("    b .L_arm64_mkeq_str\n");
    out.push_str(".L_arm64_mkeq_true:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_mkeq_false:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n\n");

    // fn_strcmp
    out.push_str(".align 2\n");
    out.push_str(".global fn_strcmp\n");
    out.push_str("fn_strcmp:\n");
    out.push_str("    cmp x0, x1\n");
    out.push_str("    b.eq .L_arm64_strcmp_eq\n");
    out.push_str("    cmp x0, #65536\n");
    out.push_str("    b.lo .L_arm64_strcmp_s1_null\n");
    out.push_str("    cmp x1, #65536\n");
    out.push_str("    b.lo .L_arm64_strcmp_s2_null\n");
    out.push_str(".L_arm64_strcmp_loop:\n");
    out.push_str("    ldrb w9, [x0], #1\n");
    out.push_str("    ldrb w10, [x1], #1\n");
    out.push_str("    cmp w9, w10\n");
    out.push_str("    b.ne .L_arm64_strcmp_diff\n");
    out.push_str("    cbz w9, .L_arm64_strcmp_eq\n");
    out.push_str("    b .L_arm64_strcmp_loop\n");
    out.push_str(".L_arm64_strcmp_diff:\n");
    out.push_str("    sub w0, w9, w10\n");
    out.push_str("    sxtw x0, w0\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_strcmp_s1_null:\n");
    out.push_str("    cmp x1, #65536\n");
    out.push_str("    b.lo .L_arm64_strcmp_eq\n");
    out.push_str("    mov x0, #-1\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_strcmp_s2_null:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_strcmp_eq:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n\n");

    // fn_map
    out.push_str(".align 2\n");
    out.push_str(".global fn_map\n");
    out.push_str("fn_map:\n");
    out.push_str("    stp x29, x30, [sp, #-32]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    mov x1, #40\n");
    out.push_str(&format!("    bl {}calloc\n", p));
    out.push_str("    movz x1, #0x0002\n");
    out.push_str("    movk x1, #0x5A11, lsl #16\n");
    out.push_str("    str x1, [x0]\n");
    out.push_str("    mov x1, #1\n");
    out.push_str("    str x1, [x0, #8]\n");
    out.push_str("    add x19, x0, #16\n");
    out.push_str("    str xzr, [x19]\n");
    out.push_str("    mov x1, #64\n");
    out.push_str("    str x1, [x19, #8]\n");
    out.push_str("    mov x0, #64\n");
    out.push_str("    mov x1, #24\n");
    out.push_str(&format!("    bl {}calloc\n", p));
    out.push_str("    str x0, [x19, #16]\n");
    out.push_str("    mov x1, #1576\n");
    emit_adrp_add(out, "x2", "alya_allocated_bytes", os);
    out.push_str("    ldr x3, [x2]\n");
    out.push_str("    add x3, x3, x1\n");
    out.push_str("    str x3, [x2]\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    mov x2, #2\n");
    out.push_str("    mov x3, #0\n");
    out.push_str("    stp x0, x1, [sp, #-16]!\n");
    out.push_str("    bl alya_mem_track_alloc\n");
    out.push_str("    ldp x0, x1, [sp], #16\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #32\n");
    out.push_str("    ret\n\n");

    // fn_set
    out.push_str(".align 2\n");
    out.push_str(".global fn_set\n");
    out.push_str("fn_set:\n");
    out.push_str("    stp x29, x30, [sp, #-80]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    stp x23, x24, [sp, #48]\n");
    out.push_str("    stp x25, x26, [sp, #64]\n");
    out.push_str("    cbz x0, .L_arm64_set_done\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    mov x21, x2\n");
    out.push_str("    ldr x9, [x19]\n");
    out.push_str("    lsl x9, x9, #1\n");
    out.push_str("    ldr x10, [x19, #8]\n");
    out.push_str("    cmp x9, x10\n");
    out.push_str("    b.lt .L_arm64_set_no_resize\n");
    out.push_str("    lsl x0, x10, #1\n");
    out.push_str("    mov x22, x0\n");
    out.push_str("    mov x1, #24\n");
    out.push_str(&format!("    bl {}calloc\n", p));
    out.push_str("    mov x26, x0\n");
    out.push_str("    mov x1, #24\n");
    out.push_str("    mul x1, x22, x1\n");
    emit_adrp_add(out, "x2", "alya_allocated_bytes", os);
    out.push_str("    ldr x3, [x2]\n");
    out.push_str("    add x3, x3, x1\n");
    out.push_str("    str x3, [x2]\n");
    out.push_str("    sub x23, x22, #1\n");
    out.push_str("    mov x24, #0\n");
    out.push_str("    ldr x25, [x19, #8]\n");
    out.push_str(".L_arm64_rehash_loop:\n");
    out.push_str("    cmp x24, x25\n");
    out.push_str("    b.ge .L_arm64_rehash_done\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x24, x24, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x11, [x10, #16]\n");
    out.push_str("    cmp x11, #1\n");
    out.push_str("    b.ne .L_arm64_rehash_next\n");
    out.push_str("    ldr x0, [x10]\n");
    out.push_str("    bl alya_map_hash\n");
    out.push_str("    and x0, x0, x23\n");
    out.push_str(".L_arm64_rehash_probe:\n");
    out.push_str("    add x9, x0, x0, lsl #1\n");
    out.push_str("    add x9, x26, x9, lsl #3\n");
    out.push_str("    ldr x11, [x9, #16]\n");
    out.push_str("    cbz x11, .L_arm64_rehash_put\n");
    out.push_str("    add x0, x0, #1\n");
    out.push_str("    and x0, x0, x23\n");
    out.push_str("    b .L_arm64_rehash_probe\n");
    out.push_str(".L_arm64_rehash_put:\n");
    out.push_str("    ldr x12, [x19, #16]\n");
    out.push_str("    add x10, x24, x24, lsl #1\n");
    out.push_str("    add x10, x12, x10, lsl #3\n");
    out.push_str("    ldr x11, [x10]\n");
    out.push_str("    str x11, [x9]\n");
    out.push_str("    ldr x11, [x10, #8]\n");
    out.push_str("    str x11, [x9, #8]\n");
    out.push_str("    mov x11, #1\n");
    out.push_str("    str x11, [x9, #16]\n");
    out.push_str(".L_arm64_rehash_next:\n");
    out.push_str("    add x24, x24, #1\n");
    out.push_str("    b .L_arm64_rehash_loop\n");
    out.push_str(".L_arm64_rehash_done:\n");
    out.push_str("    str x22, [x19, #8]\n");
    out.push_str("    str x26, [x19, #16]\n");
    out.push_str(".L_arm64_set_no_resize:\n");
    out.push_str("    ldr x9, [x19, #8]\n");
    out.push_str("    sub x22, x9, #1\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    bl alya_map_hash\n");
    out.push_str("    and x23, x0, x22\n");
    out.push_str("    mov x24, #-1\n");
    out.push_str("    mov x25, #0\n");
    out.push_str(".L_arm64_set_probe:\n");
    out.push_str("    ldr x9, [x19, #8]\n");
    out.push_str("    cmp x25, x9\n");
    out.push_str("    b.ge .L_arm64_set_use_tomb\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x23, x23, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x11, [x10, #16]\n");
    out.push_str("    cbz x11, .L_arm64_set_empty\n");
    out.push_str("    cmp x11, #2\n");
    out.push_str("    b.ne .L_arm64_set_check_key\n");
    out.push_str("    cmn x24, #1\n");
    out.push_str("    b.ne .L_arm64_set_next\n");
    out.push_str("    mov x24, x23\n");
    out.push_str("    b .L_arm64_set_next\n");
    out.push_str(".L_arm64_set_check_key:\n");
    out.push_str("    ldr x0, [x10]\n");
    out.push_str("    mov x1, x20\n");
    out.push_str("    bl alya_map_key_eq\n");
    out.push_str("    cbz x0, .L_arm64_set_next\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x23, x23, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    str x21, [x10, #8]\n");
    out.push_str("    b .L_arm64_set_done\n");
    out.push_str(".L_arm64_set_next:\n");
    out.push_str("    add x25, x25, #1\n");
    out.push_str("    add x23, x23, #1\n");
    out.push_str("    and x23, x23, x22\n");
    out.push_str("    b .L_arm64_set_probe\n");
    out.push_str(".L_arm64_set_empty:\n");
    out.push_str("    cmn x24, #1\n");
    out.push_str("    b.eq .L_arm64_set_insert_here\n");
    out.push_str(".L_arm64_set_use_tomb:\n");
    out.push_str("    cmn x24, #1\n");
    out.push_str("    b.eq .L_arm64_set_done\n");
    out.push_str("    mov x23, x24\n");
    out.push_str(".L_arm64_set_insert_here:\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x23, x23, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    str x20, [x10]\n");
    out.push_str("    str x21, [x10, #8]\n");
    out.push_str("    mov x11, #1\n");
    out.push_str("    str x11, [x10, #16]\n");
    out.push_str("    ldr x9, [x19]\n");
    out.push_str("    add x9, x9, #1\n");
    out.push_str("    str x9, [x19]\n");
    out.push_str(".L_arm64_set_done:\n");
    out.push_str("    ldp x25, x26, [sp, #64]\n");
    out.push_str("    ldp x23, x24, [sp, #48]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #80\n");
    out.push_str("    ret\n\n");

    // fn_get
    out.push_str(".align 2\n");
    out.push_str(".global fn_get\n");
    out.push_str("fn_get:\n");
    out.push_str("    stp x29, x30, [sp, #-64]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    stp x23, x24, [sp, #48]\n");
    out.push_str("    mov x24, x2\n");
    out.push_str("    cbz x0, .L_arm64_get_not_found\n");
    out.push_str("    cmp x0, #65536\n");
    out.push_str("    b.lo .L_arm64_get_not_found\n");
    out.push_str("    tst x0, #7\n");
    out.push_str("    b.ne .L_arm64_get_not_found\n");
    emit_adrp_add(out, "x9", "alya_rodata_start", os);
    out.push_str("    cmp x0, x9\n");
    out.push_str("    b.lo .L_arm64_get_chk_str_buf\n");
    emit_adrp_add(out, "x10", "alya_rodata_end", os);
    out.push_str("    cmp x0, x10\n");
    out.push_str("    b.lo .L_arm64_get_not_found\n");
    out.push_str(".L_arm64_get_chk_str_buf:\n");
    emit_adrp_add(out, "x9", "alya_str_buf", os);
    out.push_str("    cmp x0, x9\n");
    out.push_str("    b.lo .L_arm64_get_chk_tag\n");
    out.push_str("    movz x10, #1024, lsl #16\n");
    out.push_str("    add x10, x9, x10\n");
    out.push_str("    cmp x0, x10\n");
    out.push_str("    b.lo .L_arm64_get_not_found\n");
    out.push_str(".L_arm64_get_chk_tag:\n");
    out.push_str("    ldur w9, [x0, #-16]\n");
    out.push_str("    movz w10, #0x0001\n");
    out.push_str("    movk w10, #0x5A11, lsl #16\n");
    out.push_str("    cmp w9, w10\n");
    out.push_str("    b.eq .L_arm64_get_array\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    bl alya_map_hash\n");
    out.push_str("    ldr x9, [x19, #8]\n");
    out.push_str("    sub x22, x9, #1\n");
    out.push_str("    and x21, x0, x22\n");
    out.push_str("    mov x23, #0\n");
    out.push_str(".L_arm64_get_loop:\n");
    out.push_str("    ldr x9, [x19, #8]\n");
    out.push_str("    cmp x23, x9\n");
    out.push_str("    b.ge .L_arm64_get_not_found\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x11, [x10, #16]\n");
    out.push_str("    cbz x11, .L_arm64_get_not_found\n");
    out.push_str("    cmp x11, #1\n");
    out.push_str("    b.ne .L_arm64_get_next\n");
    out.push_str("    ldr x0, [x10]\n");
    out.push_str("    mov x1, x20\n");
    out.push_str("    bl alya_map_key_eq\n");
    out.push_str("    cbnz x0, .L_arm64_get_found\n");
    out.push_str(".L_arm64_get_next:\n");
    out.push_str("    add x21, x21, #1\n");
    out.push_str("    and x21, x21, x22\n");
    out.push_str("    add x23, x23, #1\n");
    out.push_str("    b .L_arm64_get_loop\n");
    out.push_str(".L_arm64_get_found:\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x0, [x10, #8]\n");
    out.push_str("    b .L_arm64_get_ret\n");
    out.push_str(".L_arm64_get_array:\n");
    out.push_str("    cmp x1, #0\n");
    out.push_str("    b.lt .L_arm64_get_not_found\n");
    out.push_str("    ldr x9, [x0]\n");
    out.push_str("    cmp x1, x9\n");
    out.push_str("    b.ge .L_arm64_get_not_found\n");
    out.push_str("    ldr x10, [x0, #16]\n");
    out.push_str("    ldr x0, [x10, x1, lsl #3]\n");
    out.push_str("    b .L_arm64_get_ret\n");
    out.push_str(".L_arm64_get_not_found:\n");
    out.push_str("    mov x0, x24\n");
    out.push_str(".L_arm64_get_ret:\n");
    out.push_str("    ldp x23, x24, [sp, #48]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #64\n");
    out.push_str("    ret\n\n");

    // fn_has
    out.push_str(".align 2\n");
    out.push_str(".global fn_has\n");
    out.push_str("fn_has:\n");
    out.push_str("    stp x29, x30, [sp, #-64]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    stp x23, x24, [sp, #48]\n");
    out.push_str("    cbz x0, .L_arm64_has_not_found\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    bl alya_map_hash\n");
    out.push_str("    ldr x9, [x19, #8]\n");
    out.push_str("    sub x22, x9, #1\n");
    out.push_str("    and x21, x0, x22\n");
    out.push_str("    mov x23, #0\n");
    out.push_str(".L_arm64_has_loop:\n");
    out.push_str("    ldr x9, [x19, #8]\n");
    out.push_str("    cmp x23, x9\n");
    out.push_str("    b.ge .L_arm64_has_not_found\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x11, [x10, #16]\n");
    out.push_str("    cbz x11, .L_arm64_has_not_found\n");
    out.push_str("    cmp x11, #1\n");
    out.push_str("    b.ne .L_arm64_has_next\n");
    out.push_str("    ldr x0, [x10]\n");
    out.push_str("    mov x1, x20\n");
    out.push_str("    bl alya_map_key_eq\n");
    out.push_str("    cbnz x0, .L_arm64_has_found\n");
    out.push_str(".L_arm64_has_next:\n");
    out.push_str("    add x21, x21, #1\n");
    out.push_str("    and x21, x21, x22\n");
    out.push_str("    add x23, x23, #1\n");
    out.push_str("    b .L_arm64_has_loop\n");
    out.push_str(".L_arm64_has_found:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    b .L_arm64_has_ret\n");
    out.push_str(".L_arm64_has_not_found:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str(".L_arm64_has_ret:\n");
    out.push_str("    ldp x23, x24, [sp, #48]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #64\n");
    out.push_str("    ret\n\n");

    // fn_remove
    out.push_str(".align 2\n");
    out.push_str(".global fn_remove\n");
    out.push_str("fn_remove:\n");
    out.push_str("    stp x29, x30, [sp, #-64]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    stp x23, x24, [sp, #48]\n");
    out.push_str("    cbz x0, .L_arm64_rem_not_found\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    bl alya_map_hash\n");
    out.push_str("    ldr x9, [x19, #8]\n");
    out.push_str("    sub x22, x9, #1\n");
    out.push_str("    and x21, x0, x22\n");
    out.push_str("    mov x23, #0\n");
    out.push_str(".L_arm64_rem_loop:\n");
    out.push_str("    ldr x9, [x19, #8]\n");
    out.push_str("    cmp x23, x9\n");
    out.push_str("    b.ge .L_arm64_rem_not_found\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x11, [x10, #16]\n");
    out.push_str("    cbz x11, .L_arm64_rem_not_found\n");
    out.push_str("    cmp x11, #1\n");
    out.push_str("    b.ne .L_arm64_rem_next\n");
    out.push_str("    ldr x0, [x10]\n");
    out.push_str("    mov x1, x20\n");
    out.push_str("    bl alya_map_key_eq\n");
    out.push_str("    cbnz x0, .L_arm64_rem_found\n");
    out.push_str(".L_arm64_rem_next:\n");
    out.push_str("    add x21, x21, #1\n");
    out.push_str("    and x21, x21, x22\n");
    out.push_str("    add x23, x23, #1\n");
    out.push_str("    b .L_arm64_rem_loop\n");
    out.push_str(".L_arm64_rem_found:\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    mov x11, #2\n");
    out.push_str("    str x11, [x10, #16]\n");
    out.push_str("    ldr x9, [x19]\n");
    out.push_str("    sub x9, x9, #1\n");
    out.push_str("    str x9, [x19]\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    b .L_arm64_rem_ret\n");
    out.push_str(".L_arm64_rem_not_found:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str(".L_arm64_rem_ret:\n");
    out.push_str("    ldp x23, x24, [sp, #48]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #64\n");
    out.push_str("    ret\n\n");

    // fn_keys
    out.push_str(".align 2\n");
    out.push_str(".global fn_keys\n");
    out.push_str("fn_keys:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    bl alya_array_new\n");
    out.push_str("    mov x20, x0\n");
    out.push_str("    cbz x19, .L_arm64_keys_done\n");
    out.push_str("    mov x21, #0\n");
    out.push_str("    ldr x22, [x19, #8]\n");
    out.push_str(".L_arm64_keys_loop:\n");
    out.push_str("    cmp x21, x22\n");
    out.push_str("    b.ge .L_arm64_keys_done\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x11, [x10, #16]\n");
    out.push_str("    cmp x11, #1\n");
    out.push_str("    b.ne .L_arm64_keys_next\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    ldr x1, [x10]\n");
    out.push_str("    bl alya_array_push\n");
    out.push_str(".L_arm64_keys_next:\n");
    out.push_str("    add x21, x21, #1\n");
    out.push_str("    b .L_arm64_keys_loop\n");
    out.push_str(".L_arm64_keys_done:\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_values
    out.push_str(".align 2\n");
    out.push_str(".global fn_values\n");
    out.push_str("fn_values:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    bl alya_array_new\n");
    out.push_str("    mov x20, x0\n");
    out.push_str("    cbz x19, .L_arm64_vals_done\n");
    out.push_str("    mov x21, #0\n");
    out.push_str("    ldr x22, [x19, #8]\n");
    out.push_str(".L_arm64_vals_loop:\n");
    out.push_str("    cmp x21, x22\n");
    out.push_str("    b.ge .L_arm64_vals_done\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x11, [x10, #16]\n");
    out.push_str("    cmp x11, #1\n");
    out.push_str("    b.ne .L_arm64_vals_next\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    ldr x1, [x10, #8]\n");
    out.push_str("    bl alya_array_push\n");
    out.push_str(".L_arm64_vals_next:\n");
    out.push_str("    add x21, x21, #1\n");
    out.push_str("    b .L_arm64_vals_loop\n");
    out.push_str(".L_arm64_vals_done:\n");
    out.push_str("    mov x0, x20\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // alya_print_map
    out.push_str(".align 2\n");
    out.push_str(".global alya_print_map\n");
    out.push_str("alya_print_map:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    cbnz x19, .L_arm64_pmap_not_null\n");
    emit_adrp_add(out, "x0", "alya_fmt_map_null", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str("    b .L_arm64_pmap_exit\n");
    out.push_str(".L_arm64_pmap_not_null:\n");
    out.push_str("    ldr x9, [x19]\n");
    out.push_str("    cbnz x9, .L_arm64_pmap_has_items\n");
    emit_adrp_add(out, "x0", "alya_fmt_map_empty", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str("    b .L_arm64_pmap_exit\n");
    out.push_str(".L_arm64_pmap_has_items:\n");
    emit_adrp_add(out, "x0", "alya_fmt_map_open", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str("    mov x20, #0\n");
    out.push_str("    mov x21, #0\n");
    out.push_str("    ldr x22, [x19, #8]\n");
    out.push_str(".L_arm64_pmap_loop:\n");
    out.push_str("    cmp x21, x22\n");
    out.push_str("    b.ge .L_arm64_pmap_close\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x11, [x10, #16]\n");
    out.push_str("    cmp x11, #1\n");
    out.push_str("    b.ne .L_arm64_pmap_next\n");
    out.push_str("    cbz x20, .L_arm64_pmap_print_pair\n");
    emit_adrp_add(out, "x0", "alya_fmt_arr_comma", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str(".L_arm64_pmap_print_pair:\n");
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x1, [x10]\n");
    out.push_str("    cmp x1, #256\n");
    out.push_str("    b.lo .L_arm64_pmap_key_num\n");
    emit_adrp_add(out, "x0", "alya_fmt_prompt", os);
    if matches!(os, OperatingSystem::MacOS) {
        out.push_str("    sub sp, sp, #16\n");
        out.push_str("    str x1, [sp]\n");
        out.push_str(&format!("    bl {}printf\n", p));
        out.push_str("    add sp, sp, #16\n");
    } else {
        out.push_str(&format!("    bl {}printf\n", p));
    }
    out.push_str("    b .L_arm64_pmap_colon\n");
    out.push_str(".L_arm64_pmap_key_num:\n");
    emit_adrp_add(out, "x0", "alya_fmt_arr_elem", os);
    if matches!(os, OperatingSystem::MacOS) {
        out.push_str("    sub sp, sp, #16\n");
        out.push_str("    str x1, [sp]\n");
        out.push_str(&format!("    bl {}printf\n", p));
        out.push_str("    add sp, sp, #16\n");
    } else {
        out.push_str(&format!("    bl {}printf\n", p));
    }
    out.push_str(".L_arm64_pmap_colon:\n");
    emit_adrp_add(out, "x0", "alya_fmt_map_colon", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str("    ldr x9, [x19, #16]\n");
    out.push_str("    add x10, x21, x21, lsl #1\n");
    out.push_str("    add x10, x9, x10, lsl #3\n");
    out.push_str("    ldr x1, [x10, #8]\n");
    emit_adrp_add(out, "x0", "alya_fmt_arr_elem", os);
    if matches!(os, OperatingSystem::MacOS) {
        out.push_str("    sub sp, sp, #16\n");
        out.push_str("    str x1, [sp]\n");
        out.push_str(&format!("    bl {}printf\n", p));
        out.push_str("    add sp, sp, #16\n");
    } else {
        out.push_str(&format!("    bl {}printf\n", p));
    }
    out.push_str("    add x20, x20, #1\n");
    out.push_str(".L_arm64_pmap_next:\n");
    out.push_str("    add x21, x21, #1\n");
    out.push_str("    b .L_arm64_pmap_loop\n");
    out.push_str(".L_arm64_pmap_close:\n");
    emit_adrp_add(out, "x0", "alya_fmt_map_close", os);
    out.push_str(&format!("    bl {}printf\n", p));
    out.push_str(".L_arm64_pmap_exit:\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_in(collection, item)
    out.push_str(".global fn_in\n");
    out.push_str("fn_in:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    cbz x19, .L_arm64_in_zero\n");
    out.push_str("    tst x19, #7\n");
    out.push_str("    b.ne .L_arm64_in_str\n");
    out.push_str("    mov x2, #65536\n");
    out.push_str("    cmp x19, x2\n");
    out.push_str("    b.lo .L_arm64_in_str\n");
    emit_adrp_add(out, "x2", "alya_rodata_start", os);
    out.push_str("    cmp x19, x2\n");
    out.push_str("    b.lo .L_arm64_in_chk_str_buf\n");
    emit_adrp_add(out, "x3", "alya_rodata_end", os);
    out.push_str("    cmp x19, x3\n");
    out.push_str("    b.lo .L_arm64_in_str\n");
    out.push_str(".L_arm64_in_chk_str_buf:\n");
    emit_adrp_add(out, "x2", "alya_str_buf", os);
    out.push_str("    cmp x19, x2\n");
    out.push_str("    b.lo .L_arm64_in_chk_tag\n");
    out.push_str("    movz x3, #1024, lsl #16\n");
    out.push_str("    add x3, x2, x3\n");
    out.push_str("    cmp x19, x3\n");
    out.push_str("    b.lo .L_arm64_in_str\n");
    out.push_str(".L_arm64_in_chk_tag:\n");
    out.push_str("    ldur w2, [x19, #-16]\n");
    out.push_str("    movz w3, #0x0002\n");
    out.push_str("    movk w3, #0x5A11, lsl #16\n");
    out.push_str("    cmp w2, w3\n");
    out.push_str("    b.eq .L_arm64_in_map\n");
    out.push_str("    movz w3, #0x0001\n");
    out.push_str("    movk w3, #0x5A11, lsl #16\n");
    out.push_str("    cmp w2, w3\n");
    out.push_str("    b.eq .L_arm64_in_arr\n");
    out.push_str(".L_arm64_in_str:\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    mov x1, x20\n");
    out.push_str("    bl fn_contains\n");
    out.push_str("    b .L_arm64_in_done\n");
    out.push_str(".L_arm64_in_map:\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    mov x1, x20\n");
    out.push_str("    bl fn_has\n");
    out.push_str("    b .L_arm64_in_done\n");
    out.push_str(".L_arm64_in_arr:\n");
    out.push_str("    ldr x21, [x19]\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_in_arr_loop:\n");
    out.push_str("    cmp x22, x21\n");
    out.push_str("    b.ge .L_arm64_in_zero\n");
    out.push_str("    ldr x2, [x19, #16]\n");
    out.push_str("    ldr x0, [x2, x22, lsl #3]\n");
    out.push_str("    mov x1, x20\n");
    out.push_str("    bl alya_map_key_eq\n");
    out.push_str("    cbnz x0, .L_arm64_in_found\n");
    out.push_str("    add x22, x22, #1\n");
    out.push_str("    b .L_arm64_in_arr_loop\n");
    out.push_str(".L_arm64_in_found:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    b .L_arm64_in_done\n");
    out.push_str(".L_arm64_in_zero:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str(".L_arm64_in_done:\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");
}
