use crate::codegen::target::OperatingSystem;
use super::{emit_adrp_add, emit_str_buf_ctx};

#[rustfmt::skip]
pub fn emit(out: &mut String, os: OperatingSystem) {
    let is_win = matches!(os, OperatingSystem::Windows);
    let p = if matches!(os, OperatingSystem::MacOS) { "_" } else { "" };
    let _ = (is_win, p);

    // alya_concat
    out.push_str(".align 2\n");
    out.push_str("alya_concat:\n");
    out.push_str("    stp x29, x30, [sp, #-16]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #-16]!\n");
    out.push_str("    stp x21, x22, [sp, #-16]!\n");
    emit_str_buf_ctx(out, "x19", "x20", "x9", os);
    out.push_str("    ldr x21, [x20]\n");
    out.push_str("    movz x9, #16960\n");
    out.push_str("    movk x9, #15, lsl #16\n"); // 1,000,000
    out.push_str("    cmp x21, x9\n");
    out.push_str("    b.lo .L_arm_concat_ok\n");
    out.push_str("    mov x21, #0\n");
    out.push_str(".L_arm_concat_ok:\n");
    out.push_str("    add x22, x19, x21\n");
    out.push_str("    cmp x0, #65536\n");
    out.push_str("    b.lo .L_arm_copy2_start\n");
    out.push_str(".L_arm_copy1:\n");
    out.push_str("    ldrb w2, [x0], #1\n");
    out.push_str("    cbz w2, .L_arm_copy2_start\n");
    out.push_str("    strb w2, [x22], #1\n");
    out.push_str("    b .L_arm_copy1\n");
    out.push_str(".L_arm_copy2_start:\n");
    out.push_str("    cmp x1, #65536\n");
    out.push_str("    b.lo .L_arm_concat_end\n");
    out.push_str(".L_arm_copy2:\n");
    out.push_str("    ldrb w2, [x1], #1\n");
    out.push_str("    cbz w2, .L_arm_concat_end\n");
    out.push_str("    strb w2, [x22], #1\n");
    out.push_str("    b .L_arm_copy2\n");
    out.push_str(".L_arm_concat_end:\n");
    out.push_str("    strb wzr, [x22], #1\n");
    out.push_str("    sub x2, x22, x19\n");
    out.push_str("    add x2, x2, #7\n");
    out.push_str("    and x2, x2, #~7\n");
    out.push_str("    str x2, [x20]\n");
    out.push_str("    add x0, x19, x21\n");
    out.push_str("    ldp x21, x22, [sp], #16\n");
    out.push_str("    ldp x19, x20, [sp], #16\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n\n");

    // fn_len
    out.push_str("fn_len:\n");
    out.push_str("    mov x1, x0\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    mov x2, #65536\n");
    out.push_str("    cmp x1, x2\n");
    out.push_str("    b.lo .L_arm_len_end\n");
    out.push_str("    movz x3, #0x0001\n");
    out.push_str("    movk x3, #0x5A11, lsl #16\n");
    out.push_str("    ldr x2, [x1, #-16]\n");
    out.push_str("    cmp x2, x3\n");
    out.push_str("    b.eq .L_arm_len_obj\n");
    out.push_str("    movz x3, #0x0002\n");
    out.push_str("    movk x3, #0x5A11, lsl #16\n");
    out.push_str("    cmp x2, x3\n");
    out.push_str("    b.eq .L_arm_len_obj\n");
    out.push_str(".L_arm_len_loop:\n");
    out.push_str("    ldrb w2, [x1, x0]\n");
    out.push_str("    cbz w2, .L_arm_len_end\n");
    out.push_str("    add x0, x0, #1\n");
    out.push_str("    b .L_arm_len_loop\n");
    out.push_str(".L_arm_len_obj:\n");
    out.push_str("    ldr x0, [x1]\n");
    out.push_str(".L_arm_len_end:\n");
    out.push_str("    ret\n\n");

    // fn_upper
    out.push_str(".align 2\n");
    out.push_str("fn_upper:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    emit_str_buf_ctx(out, "x20", "x21", "x9", os);
    out.push_str("    ldr x22, [x21]\n");
    out.push_str("    movz x9, #16960\n");
    out.push_str("    movk x9, #15, lsl #16\n"); // 1,000,000
    out.push_str("    cmp x22, x9\n");
    out.push_str("    b.lo .L_arm64_upper_buf_ok\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_upper_buf_ok:\n");
    out.push_str("    add x0, x20, x22\n");
    out.push_str("    mov x10, x0\n");
    out.push_str(".L_arm64_upper_loop:\n");
    out.push_str("    ldrb w11, [x19], #1\n");
    out.push_str("    cbz w11, .L_arm64_upper_done\n");
    out.push_str("    cmp w11, #'a'\n");
    out.push_str("    b.lt .L_arm64_upper_store\n");
    out.push_str("    cmp w11, #'z'\n");
    out.push_str("    b.gt .L_arm64_upper_store\n");
    out.push_str("    sub w11, w11, #32\n");
    out.push_str(".L_arm64_upper_store:\n");
    out.push_str("    strb w11, [x10], #1\n");
    out.push_str("    b .L_arm64_upper_loop\n");
    out.push_str(".L_arm64_upper_done:\n");
    out.push_str("    strb wzr, [x10], #1\n");
    out.push_str("    sub x11, x10, x20\n");
    out.push_str("    add x11, x11, #7\n");
    out.push_str("    and x11, x11, #~7\n");
    out.push_str("    str x11, [x21]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_lower
    out.push_str(".align 2\n");
    out.push_str("fn_lower:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    emit_str_buf_ctx(out, "x20", "x21", "x9", os);
    out.push_str("    ldr x22, [x21]\n");
    out.push_str("    movz x9, #16960\n");
    out.push_str("    movk x9, #15, lsl #16\n"); // 1,000,000
    out.push_str("    cmp x22, x9\n");
    out.push_str("    b.lo .L_arm64_lower_buf_ok\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_lower_buf_ok:\n");
    out.push_str("    add x0, x20, x22\n");
    out.push_str("    mov x10, x0\n");
    out.push_str(".L_arm64_lower_loop:\n");
    out.push_str("    ldrb w11, [x19], #1\n");
    out.push_str("    cbz w11, .L_arm64_lower_done\n");
    out.push_str("    cmp w11, #'A'\n");
    out.push_str("    b.lt .L_arm64_lower_store\n");
    out.push_str("    cmp w11, #'Z'\n");
    out.push_str("    b.gt .L_arm64_lower_store\n");
    out.push_str("    add w11, w11, #32\n");
    out.push_str(".L_arm64_lower_store:\n");
    out.push_str("    strb w11, [x10], #1\n");
    out.push_str("    b .L_arm64_lower_loop\n");
    out.push_str(".L_arm64_lower_done:\n");
    out.push_str("    strb wzr, [x10], #1\n");
    out.push_str("    sub x11, x10, x20\n");
    out.push_str("    add x11, x11, #7\n");
    out.push_str("    and x11, x11, #~7\n");
    out.push_str("    str x11, [x21]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_trim
    out.push_str(".align 2\n");
    out.push_str("fn_trim:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str(".L_arm64_trim_lws:\n");
    out.push_str("    ldrb w11, [x19]\n");
    out.push_str("    cmp w11, #32\n");
    out.push_str("    b.eq .L_arm64_trim_lws_inc\n");
    out.push_str("    cmp w11, #9\n");
    out.push_str("    b.eq .L_arm64_trim_lws_inc\n");
    out.push_str("    cmp w11, #10\n");
    out.push_str("    b.eq .L_arm64_trim_lws_inc\n");
    out.push_str("    cmp w11, #13\n");
    out.push_str("    b.eq .L_arm64_trim_lws_inc\n");
    out.push_str("    b .L_arm64_trim_lws_done\n");
    out.push_str(".L_arm64_trim_lws_inc:\n");
    out.push_str("    add x19, x19, #1\n");
    out.push_str("    b .L_arm64_trim_lws\n");
    out.push_str(".L_arm64_trim_lws_done:\n");
    out.push_str("    mov x12, x19\n");
    out.push_str(".L_arm64_trim_end_loop:\n");
    out.push_str("    ldrb w11, [x12]\n");
    out.push_str("    cbz w11, .L_arm64_trim_find_end_done\n");
    out.push_str("    add x12, x12, #1\n");
    out.push_str("    b .L_arm64_trim_end_loop\n");
    out.push_str(".L_arm64_trim_find_end_done:\n");
    out.push_str(".L_arm64_trim_tws:\n");
    out.push_str("    cmp x12, x19\n");
    out.push_str("    b.le .L_arm64_trim_copy_start\n");
    out.push_str("    sub x13, x12, #1\n");
    out.push_str("    ldrb w11, [x13]\n");
    out.push_str("    cmp w11, #32\n");
    out.push_str("    b.eq .L_arm64_trim_tws_dec\n");
    out.push_str("    cmp w11, #9\n");
    out.push_str("    b.eq .L_arm64_trim_tws_dec\n");
    out.push_str("    cmp w11, #10\n");
    out.push_str("    b.eq .L_arm64_trim_tws_dec\n");
    out.push_str("    cmp w11, #13\n");
    out.push_str("    b.eq .L_arm64_trim_tws_dec\n");
    out.push_str("    b .L_arm64_trim_copy_start\n");
    out.push_str(".L_arm64_trim_tws_dec:\n");
    out.push_str("    mov x12, x13\n");
    out.push_str("    b .L_arm64_trim_tws\n");
    out.push_str(".L_arm64_trim_copy_start:\n");
    emit_str_buf_ctx(out, "x20", "x21", "x9", os);
    out.push_str("    ldr x22, [x21]\n");
    out.push_str("    movz x9, #16960\n");
    out.push_str("    movk x9, #15, lsl #16\n"); // 1,000,000
    out.push_str("    cmp x22, x9\n");
    out.push_str("    b.lo .L_arm64_trim_buf_ok\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_trim_buf_ok:\n");
    out.push_str("    add x0, x20, x22\n");
    out.push_str("    mov x10, x0\n");
    out.push_str(".L_arm64_trim_copy_loop:\n");
    out.push_str("    cmp x19, x12\n");
    out.push_str("    b.ge .L_arm64_trim_done\n");
    out.push_str("    ldrb w11, [x19], #1\n");
    out.push_str("    strb w11, [x10], #1\n");
    out.push_str("    b .L_arm64_trim_copy_loop\n");
    out.push_str(".L_arm64_trim_done:\n");
    out.push_str("    strb wzr, [x10], #1\n");
    out.push_str("    sub x11, x10, x20\n");
    out.push_str("    add x11, x11, #7\n");
    out.push_str("    and x11, x11, #~7\n");
    out.push_str("    str x11, [x21]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_substring / fn_substr
    out.push_str(".align 2\n");
    out.push_str("fn_substr:\n");
    out.push_str(".align 2\n");
    out.push_str("fn_substring:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    cmp x1, #0\n");
    out.push_str("    b.ge .L_arm64_sub_adv\n");
    out.push_str("    mov x1, #0\n");
    out.push_str(".L_arm64_sub_adv:\n");
    out.push_str("    cbz x1, .L_arm64_sub_adv_done\n");
    out.push_str("    ldrb w3, [x19]\n");
    out.push_str("    cbz w3, .L_arm64_sub_adv_done\n");
    out.push_str("    add x19, x19, #1\n");
    out.push_str("    sub x1, x1, #1\n");
    out.push_str("    b .L_arm64_sub_adv\n");
    out.push_str(".L_arm64_sub_adv_done:\n");
    emit_str_buf_ctx(out, "x20", "x21", "x9", os);
    out.push_str("    ldr x22, [x21]\n");
    out.push_str("    movz x9, #16960\n");
    out.push_str("    movk x9, #15, lsl #16\n"); // 1,000,000
    out.push_str("    cmp x22, x9\n");
    out.push_str("    b.lo .L_arm64_sub_buf_ok\n");
    out.push_str("    mov x22, #0\n");
    out.push_str(".L_arm64_sub_buf_ok:\n");
    out.push_str("    add x0, x20, x22\n");
    out.push_str("    mov x10, x0\n");
    out.push_str(".L_arm64_sub_copy:\n");
    out.push_str("    ldrb w3, [x19]\n");
    out.push_str("    cbz w3, .L_arm64_sub_done\n");
    out.push_str("    cbz x2, .L_arm64_sub_done\n");
    out.push_str("    strb w3, [x10], #1\n");
    out.push_str("    add x19, x19, #1\n");
    out.push_str("    cmp x2, #0\n");
    out.push_str("    b.lt .L_arm64_sub_copy\n");
    out.push_str("    sub x2, x2, #1\n");
    out.push_str("    b .L_arm64_sub_copy\n");
    out.push_str(".L_arm64_sub_done:\n");
    out.push_str("    strb wzr, [x10], #1\n");
    out.push_str("    sub x11, x10, x20\n");
    out.push_str("    add x11, x11, #7\n");
    out.push_str("    and x11, x11, #~7\n");
    out.push_str("    str x11, [x21]\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_char_at
    out.push_str(".align 2\n");
    out.push_str("fn_char_at:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    mov x20, x1\n");
    out.push_str("    cbz x19, .L_arm64_char_at_empty\n");
    out.push_str("    cmp x20, #0\n");
    out.push_str("    b.lt .L_arm64_char_at_empty\n");
    out.push_str(".L_arm64_char_at_adv:\n");
    out.push_str("    cbz x20, .L_arm64_char_at_fetch\n");
    out.push_str("    ldrb w2, [x19]\n");
    out.push_str("    cbz w2, .L_arm64_char_at_empty\n");
    out.push_str("    add x19, x19, #1\n");
    out.push_str("    sub x20, x20, #1\n");
    out.push_str("    b .L_arm64_char_at_adv\n");
    out.push_str(".L_arm64_char_at_fetch:\n");
    out.push_str("    ldrb w2, [x19]\n");
    out.push_str("    cbz w2, .L_arm64_char_at_empty\n");
    emit_str_buf_ctx(out, "x3", "x4", "x6", os);
    out.push_str("    ldr x5, [x4]\n");
    out.push_str("    movz x6, #16960\n");
    out.push_str("    movk x6, #15, lsl #16\n"); // 1,000,000
    out.push_str("    cmp x5, x6\n");
    out.push_str("    b.lo .L_arm64_char_at_buf_ok\n");
    out.push_str("    mov x5, #0\n");
    out.push_str(".L_arm64_char_at_buf_ok:\n");
    out.push_str("    add x0, x3, x5\n");
    out.push_str("    strb w2, [x0]\n");
    out.push_str("    strb wzr, [x0, #1]\n");
    out.push_str("    add x5, x5, #2\n");
    out.push_str("    add x5, x5, #7\n");
    out.push_str("    and x5, x5, #~7\n");
    out.push_str("    str x5, [x4]\n");
    out.push_str("    b .L_arm64_char_at_done\n");
    out.push_str(".L_arm64_char_at_empty:\n");
    emit_adrp_add(out, "x0", "alya_str_empty", os);
    out.push_str(".L_arm64_char_at_done:\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_ord / fn_char_code
    out.push_str(".align 2\n");
    out.push_str("fn_char_code:\n");
    out.push_str("fn_ord:\n");
    out.push_str("    cbz x0, .L_arm64_ord_ret\n");
    out.push_str("    cmp x0, #256\n");
    out.push_str("    b.lo .L_arm64_ord_ret\n");
    out.push_str("    ldrb w0, [x0]\n");
    out.push_str(".L_arm64_ord_ret:\n");
    out.push_str("    ret\n\n");

    // fn_chr / fn_char_from_code
    out.push_str(".align 2\n");
    out.push_str("fn_char_from_code:\n");
    out.push_str("fn_chr:\n");
    out.push_str("    stp x29, x30, [sp, #-32]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    cbz x19, .L_arm64_chr_empty\n");
    out.push_str("    cmp x19, #256\n");
    out.push_str("    b.lo .L_arm64_chr_byte\n");
    out.push_str("    ldrb w19, [x19]\n");
    out.push_str(".L_arm64_chr_byte:\n");
    out.push_str("    and w19, w19, #255\n");
    out.push_str("    cbz w19, .L_arm64_chr_empty\n");
    emit_str_buf_ctx(out, "x1", "x2", "x4", os);
    out.push_str("    ldr x3, [x2]\n");
    out.push_str("    movz x4, #16960\n");
    out.push_str("    movk x4, #15, lsl #16\n"); // 1,000,000
    out.push_str("    cmp x3, x4\n");
    out.push_str("    b.lo .L_arm64_chr_buf_ok\n");
    out.push_str("    mov x3, #0\n");
    out.push_str(".L_arm64_chr_buf_ok:\n");
    out.push_str("    add x0, x1, x3\n");
    out.push_str("    strb w19, [x0]\n");
    out.push_str("    strb wzr, [x0, #1]\n");
    out.push_str("    add x3, x3, #2\n");
    out.push_str("    add x3, x3, #7\n");
    out.push_str("    and x3, x3, #~7\n");
    out.push_str("    str x3, [x2]\n");
    out.push_str("    b .L_arm64_chr_done\n");
    out.push_str(".L_arm64_chr_empty:\n");
    emit_adrp_add(out, "x0", "alya_str_empty", os);
    out.push_str(".L_arm64_chr_done:\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #32\n");
    out.push_str("    ret\n\n");

    // fn_str
    out.push_str(".align 2\n");
    out.push_str(".global fn_str\n");
    out.push_str("fn_str:\n");
    out.push_str("    stp x29, x30, [sp, #-48]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    stp x19, x20, [sp, #16]\n");
    out.push_str("    stp x21, x22, [sp, #32]\n");
    out.push_str("    mov x19, x0\n");
    emit_adrp_add(out, "x5", "alya_str_buf", os);
    out.push_str("    cmp x19, x5\n");
    out.push_str("    b.lo .L_arm64_str_chk_rodata\n");
    out.push_str("    movz x6, #1024, lsl #16\n");
    out.push_str("    add x6, x5, x6\n");
    out.push_str("    cmp x19, x6\n");
    out.push_str("    b.hs .L_arm64_str_chk_rodata\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_str_chk_rodata:\n");
    emit_adrp_add(out, "x5", "alya_rodata_start", os);
    out.push_str("    cmp x19, x5\n");
    out.push_str("    b.lo .L_arm64_str_chk_argv\n");
    emit_adrp_add(out, "x6", "alya_rodata_end", os);
    out.push_str("    cmp x19, x6\n");
    out.push_str("    b.hs .L_arm64_str_chk_argv\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_str_chk_argv:\n");
    emit_adrp_add(out, "x5", "alya_argc", os);
    out.push_str("    ldr x5, [x5]\n");
    out.push_str("    cbz x5, .L_arm64_str_convert\n");
    emit_adrp_add(out, "x6", "alya_argv", os);
    out.push_str("    ldr x6, [x6]\n");
    out.push_str("    cbz x6, .L_arm64_str_convert\n");
    out.push_str("    mov x7, #0\n");
    out.push_str(".L_arm64_str_argv_loop:\n");
    out.push_str("    cmp x7, x5\n");
    out.push_str("    b.ge .L_arm64_str_convert\n");
    out.push_str("    ldr x8, [x6, x7, lsl #3]\n");
    out.push_str("    cmp x8, x19\n");
    out.push_str("    b.eq 1f\n");
    out.push_str("    add x7, x7, #1\n");
    out.push_str("    b .L_arm64_str_argv_loop\n");
    out.push_str("1:\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_str_convert:\n");
    emit_str_buf_ctx(out, "x1", "x2", "x4", os);
    out.push_str("    ldr x3, [x2]\n");
    out.push_str("    movz x4, #16960\n");
    out.push_str("    movk x4, #15, lsl #16\n"); // 1,000,000
    out.push_str("    cmp x3, x4\n");
    out.push_str("    b.lo .L_arm64_str_buf_ok\n");
    out.push_str("    mov x3, #0\n");
    out.push_str(".L_arm64_str_buf_ok:\n");
    out.push_str("    add x20, x1, x3\n");
    out.push_str("    mov x21, x20\n");
    out.push_str("    cbnz x19, .L_arm64_str_chk_neg\n");
    out.push_str("    mov w5, #'0'\n");
    out.push_str("    strb w5, [x20]\n");
    out.push_str("    strb wzr, [x20, #1]\n");
    out.push_str("    add x20, x20, #2\n");
    out.push_str("    b .L_arm64_str_finish\n");
    out.push_str(".L_arm64_str_chk_neg:\n");
    out.push_str("    cmp x19, #0\n");
    out.push_str("    b.ge .L_arm64_str_pos\n");
    out.push_str("    mov w5, #'-'\n");
    out.push_str("    strb w5, [x20], #1\n");
    out.push_str("    neg x19, x19\n");
    out.push_str(".L_arm64_str_pos:\n");
    out.push_str("    sub sp, sp, #32\n");
    out.push_str("    mov x22, #0\n");
    out.push_str("    mov x6, #10\n");
    out.push_str(".L_arm64_str_div_loop:\n");
    out.push_str("    udiv x7, x19, x6\n");
    out.push_str("    msub x8, x7, x6, x19\n");
    out.push_str("    add w8, w8, #'0'\n");
    out.push_str("    strb w8, [sp, x22]\n");
    out.push_str("    add x22, x22, #1\n");
    out.push_str("    mov x19, x7\n");
    out.push_str("    cbnz x19, .L_arm64_str_div_loop\n");
    out.push_str(".L_arm64_str_copy_loop:\n");
    out.push_str("    sub x22, x22, #1\n");
    out.push_str("    ldrb w8, [sp, x22]\n");
    out.push_str("    strb w8, [x20], #1\n");
    out.push_str("    cbnz x22, .L_arm64_str_copy_loop\n");
    out.push_str("    add sp, sp, #32\n");
    out.push_str("    strb wzr, [x20], #1\n");
    out.push_str(".L_arm64_str_finish:\n");
    emit_str_buf_ctx(out, "x1", "x2", "x4", os);
    out.push_str("    sub x3, x20, x1\n");
    out.push_str("    add x3, x3, #7\n");
    out.push_str("    and x3, x3, #~7\n");
    out.push_str("    str x3, [x2]\n");
    out.push_str("    mov x0, x21\n");
    out.push_str("    ldp x21, x22, [sp, #32]\n");
    out.push_str("    ldp x19, x20, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #48\n");
    out.push_str("    ret\n\n");

    // fn_is_digit
    out.push_str(".align 2\n");
    out.push_str("fn_is_digit:\n");
    out.push_str("    cbz x0, .L_arm64_is_digit_false\n");
    out.push_str("    cmp x0, #256\n");
    out.push_str("    b.lo .L_arm64_is_digit_cmp\n");
    out.push_str("    ldrb w0, [x0]\n");
    out.push_str(".L_arm64_is_digit_cmp:\n");
    out.push_str("    cmp w0, #'0'\n");
    out.push_str("    b.lo .L_arm64_is_digit_false\n");
    out.push_str("    cmp w0, #'9'\n");
    out.push_str("    b.hi .L_arm64_is_digit_false\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_is_digit_false:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n\n");

    // fn_is_alpha
    out.push_str(".align 2\n");
    out.push_str("fn_is_alpha:\n");
    out.push_str("    cbz x0, .L_arm64_is_alpha_false\n");
    out.push_str("    cmp x0, #256\n");
    out.push_str("    b.lo .L_arm64_is_alpha_cmp\n");
    out.push_str("    ldrb w0, [x0]\n");
    out.push_str(".L_arm64_is_alpha_cmp:\n");
    out.push_str("    cmp w0, #'_'\n");
    out.push_str("    b.eq .L_arm64_is_alpha_true\n");
    out.push_str("    cmp w0, #'a'\n");
    out.push_str("    b.lo .L_arm64_is_alpha_upper\n");
    out.push_str("    cmp w0, #'z'\n");
    out.push_str("    b.ls .L_arm64_is_alpha_true\n");
    out.push_str(".L_arm64_is_alpha_upper:\n");
    out.push_str("    cmp w0, #'A'\n");
    out.push_str("    b.lo .L_arm64_is_alpha_false\n");
    out.push_str("    cmp w0, #'Z'\n");
    out.push_str("    b.ls .L_arm64_is_alpha_true\n");
    out.push_str(".L_arm64_is_alpha_false:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_is_alpha_true:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    ret\n\n");

    // fn_is_alnum
    out.push_str(".align 2\n");
    out.push_str("fn_is_alnum:\n");
    out.push_str("    stp x29, x30, [sp, #-32]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str("    str x19, [sp, #16]\n");
    out.push_str("    mov x19, x0\n");
    out.push_str("    bl fn_is_alpha\n");
    out.push_str("    cbnz x0, .L_arm64_is_alnum_done\n");
    out.push_str("    mov x0, x19\n");
    out.push_str("    bl fn_is_digit\n");
    out.push_str(".L_arm64_is_alnum_done:\n");
    out.push_str("    ldr x19, [sp, #16]\n");
    out.push_str("    ldp x29, x30, [sp], #32\n");
    out.push_str("    ret\n\n");

    // fn_is_space / fn_is_whitespace
    out.push_str(".align 2\n");
    out.push_str("fn_is_whitespace:\n");
    out.push_str("fn_is_space:\n");
    out.push_str("    cbz x0, .L_arm64_is_space_false\n");
    out.push_str("    cmp x0, #256\n");
    out.push_str("    b.lo .L_arm64_is_space_cmp\n");
    out.push_str("    ldrb w0, [x0]\n");
    out.push_str(".L_arm64_is_space_cmp:\n");
    out.push_str("    cmp w0, #' '\n");
    out.push_str("    b.eq .L_arm64_is_space_true\n");
    out.push_str("    cmp w0, #9\n");
    out.push_str("    b.eq .L_arm64_is_space_true\n");
    out.push_str("    cmp w0, #10\n");
    out.push_str("    b.eq .L_arm64_is_space_true\n");
    out.push_str("    cmp w0, #13\n");
    out.push_str("    b.eq .L_arm64_is_space_true\n");
    out.push_str(".L_arm64_is_space_false:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm64_is_space_true:\n");
    out.push_str("    mov x0, #1\n");
    out.push_str("    ret\n\n");

    // fn_str_to_int
    out.push_str(".align 2\n");
    out.push_str(".globl fn_str_to_int\n");
    out.push_str("fn_str_to_int:\n");
    out.push_str("    cbz x0, .L_arm_s2i_zero\n");
    emit_adrp_add(out, "x5", "alya_str_buf", os);
    out.push_str("    cmp x0, x5\n");
    out.push_str("    b.lo .L_arm_s2i_chk_rodata\n");
    out.push_str("    movz x6, #1024, lsl #16\n");
    out.push_str("    add x6, x5, x6\n");
    out.push_str("    cmp x0, x6\n");
    out.push_str("    b.lo .L_arm_s2i_is_str\n");
    out.push_str(".L_arm_s2i_chk_rodata:\n");
    emit_adrp_add(out, "x5", "alya_rodata_start", os);
    out.push_str("    cmp x0, x5\n");
    out.push_str("    b.lo .L_arm_s2i_not_str\n");
    emit_adrp_add(out, "x6", "alya_rodata_end", os);
    out.push_str("    cmp x0, x6\n");
    out.push_str("    b.lo .L_arm_s2i_is_str\n");
    out.push_str(".L_arm_s2i_not_str:\n");
    out.push_str("    lsr x2, x0, #52\n");
    out.push_str("    and x2, x2, #0x7ff\n");
    out.push_str("    cbz x2, .L_arm_s2i_check_ptr\n");
    out.push_str("    mov x3, #0x7ff\n");
    out.push_str("    cmp x2, x3\n");
    out.push_str("    b.eq .L_arm_s2i_done\n");
    out.push_str("    fmov d0, x0\n");
    out.push_str("    fcvtzs x0, d0\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm_s2i_check_ptr:\n");
    out.push_str("    movz x3, #1, lsl #16\n");
    out.push_str("    cmp x0, x3\n");
    out.push_str("    b.lo .L_arm_s2i_done\n");
    out.push_str("    b .L_arm_s2i_is_str\n");
    out.push_str(".L_arm_s2i_is_str:\n");
    out.push_str("    mov x1, x0\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    mov x2, #0\n");
    out.push_str(".L_arm_s2i_skip:\n");
    out.push_str("    ldrb w3, [x1]\n");
    out.push_str("    cbz w3, .L_arm_s2i_done\n");
    out.push_str("    cmp w3, #' '\n");
    out.push_str("    b.eq .L_arm_s2i_next\n");
    out.push_str("    cmp w3, #9\n");
    out.push_str("    b.eq .L_arm_s2i_next\n");
    out.push_str("    cmp w3, #10\n");
    out.push_str("    b.eq .L_arm_s2i_next\n");
    out.push_str("    cmp w3, #13\n");
    out.push_str("    b.eq .L_arm_s2i_next\n");
    out.push_str("    b .L_arm_s2i_sign\n");
    out.push_str(".L_arm_s2i_next:\n");
    out.push_str("    add x1, x1, #1\n");
    out.push_str("    b .L_arm_s2i_skip\n");
    out.push_str(".L_arm_s2i_sign:\n");
    out.push_str("    cmp w3, #'-'\n");
    out.push_str("    b.ne .L_arm_s2i_check_plus\n");
    out.push_str("    mov x2, #1\n");
    out.push_str("    add x1, x1, #1\n");
    out.push_str("    b .L_arm_s2i_digits\n");
    out.push_str(".L_arm_s2i_check_plus:\n");
    out.push_str("    cmp w3, #'+'\n");
    out.push_str("    b.ne .L_arm_s2i_digits\n");
    out.push_str("    add x1, x1, #1\n");
    out.push_str(".L_arm_s2i_digits:\n");
    out.push_str("    ldrb w3, [x1]\n");
    out.push_str("    sub w4, w3, #'0'\n");
    out.push_str("    cmp w4, #9\n");
    out.push_str("    b.hi .L_arm_s2i_apply_sign\n");
    out.push_str("    mov x5, #10\n");
    out.push_str("    mul x0, x0, x5\n");
    out.push_str("    add x0, x0, x4\n");
    out.push_str("    add x1, x1, #1\n");
    out.push_str("    b .L_arm_s2i_digits\n");
    out.push_str(".L_arm_s2i_apply_sign:\n");
    out.push_str("    cbz x2, .L_arm_s2i_done\n");
    out.push_str("    neg x0, x0\n");
    out.push_str(".L_arm_s2i_done:\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm_s2i_zero:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n\n");

    // fn_str_to_float
    out.push_str(".align 2\n");
    out.push_str(".globl fn_str_to_float\n");
    out.push_str("fn_str_to_float:\n");
    out.push_str("    cbz x0, .L_arm_s2f_zero\n");
    emit_adrp_add(out, "x5", "alya_str_buf", os);
    out.push_str("    cmp x0, x5\n");
    out.push_str("    b.lo .L_arm_s2f_chk_rodata\n");
    out.push_str("    movz x6, #1024, lsl #16\n");
    out.push_str("    add x6, x5, x6\n");
    out.push_str("    cmp x0, x6\n");
    out.push_str("    b.lo .L_arm_s2f_call_atof\n");
    out.push_str(".L_arm_s2f_chk_rodata:\n");
    emit_adrp_add(out, "x5", "alya_rodata_start", os);
    out.push_str("    cmp x0, x5\n");
    out.push_str("    b.lo .L_arm_s2f_not_str\n");
    emit_adrp_add(out, "x6", "alya_rodata_end", os);
    out.push_str("    cmp x0, x6\n");
    out.push_str("    b.lo .L_arm_s2f_call_atof\n");
    out.push_str(".L_arm_s2f_not_str:\n");
    out.push_str("    lsr x2, x0, #52\n");
    out.push_str("    and x2, x2, #0x7ff\n");
    out.push_str("    cbz x2, .L_arm_s2f_check_ptr\n");
    out.push_str("    mov x3, #0x7ff\n");
    out.push_str("    cmp x2, x3\n");
    out.push_str("    b.eq .L_arm_s2f_from_int\n");
    out.push_str("    fmov d0, x0\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm_s2f_check_ptr:\n");
    out.push_str("    movz x3, #1, lsl #16\n");
    out.push_str("    cmp x0, x3\n");
    out.push_str("    b.lo .L_arm_s2f_from_int\n");
    out.push_str("    b .L_arm_s2f_call_atof\n");
    out.push_str(".L_arm_s2f_from_int:\n");
    out.push_str("    scvtf d0, x0\n");
    out.push_str("    fmov x0, d0\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm_s2f_call_atof:\n");
    out.push_str("    stp x29, x30, [sp, #-16]!\n");
    out.push_str("    mov x29, sp\n");
    out.push_str(&format!("    bl {}atof\n", p));
    out.push_str("    fmov x0, d0\n");
    out.push_str("    ldp x29, x30, [sp], #16\n");
    out.push_str("    ret\n");
    out.push_str(".L_arm_s2f_zero:\n");
    out.push_str("    mov x0, #0\n");
    out.push_str("    ret\n\n");
}
