use crate::codegen::target::OperatingSystem;

#[rustfmt::skip]
pub fn emit(out: &mut String, os: OperatingSystem) {
    let is_win = matches!(os, OperatingSystem::Windows);
    let p = if matches!(os, OperatingSystem::MacOS) { "_" } else { "" };
    let _ = (is_win, p);

    // alya_array_new
    out.push_str("alya_array_new:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov %esi, %ebx\n");
    out.push_str("    cmp $8, %ebx\n");
    out.push_str("    jge .L_x86_new_cap_ok\n");
    out.push_str("    mov $8, %ebx\n");
    out.push_str("    jmp .L_x86_new_alloc_hdr\n");
    out.push_str(".L_x86_new_cap_ok:\n");
    out.push_str("    shl $1, %ebx\n");
    out.push_str(".L_x86_new_alloc_hdr:\n");
    out.push_str("    push $20\n");
    out.push_str("    push $1\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    movl $0x5A110001, (%eax)\n");
    out.push_str("    movl $1, 4(%eax)\n");
    out.push_str("    lea 8(%eax), %edi\n");
    out.push_str("    push $4\n");
    out.push_str("    push %ebx\n");
    out.push_str("    call calloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %ebx, %edx\n");
    out.push_str("    shl $2, %edx\n");
    out.push_str("    add $20, %edx\n");
    out.push_str("    add %edx, alya_allocated_bytes\n");
    out.push_str("    mov %esi, (%edi)\n");
    out.push_str("    mov %ebx, 4(%edi)\n");
    out.push_str("    mov %eax, 8(%edi)\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_array_push
    out.push_str("alya_array_push:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %edi\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    mov 4(%esi), %ebx\n");
    out.push_str("    cmp %ebx, %eax\n");
    out.push_str("    jl .L_x86_push_store\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jnz .L_x86_push_double\n");
    out.push_str("    mov $8, %ebx\n");
    out.push_str("    jmp .L_x86_push_realloc\n");
    out.push_str(".L_x86_push_double:\n");
    out.push_str("    shl $1, %ebx\n");
    out.push_str(".L_x86_push_realloc:\n");
    out.push_str("    mov %ebx, 4(%esi)\n");
    out.push_str("    lea (, %ebx, 4), %eax\n");
    out.push_str("    push %eax\n");
    out.push_str("    push 8(%esi)\n");
    out.push_str("    call realloc\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    mov %eax, 8(%esi)\n");
    out.push_str("    mov %ebx, %edx\n");
    out.push_str("    shl $2, %edx\n");
    out.push_str("    add %edx, alya_allocated_bytes\n");
    out.push_str(".L_x86_push_store:\n");
    out.push_str("    mov 8(%esi), %edx\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    mov %edi, (%edx, %eax, 4)\n");
    out.push_str("    inc %eax\n");
    out.push_str("    mov %eax, (%esi)\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_array_pop
    out.push_str("alya_array_pop:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %ebx\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov (%esi), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jle alya_error_index_out_of_bounds\n");
    out.push_str("    dec %eax\n");
    out.push_str("    mov %eax, (%esi)\n");
    out.push_str("    mov 8(%esi), %edx\n");
    out.push_str("    mov (%edx, %eax, 4), %eax\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    pop %esi\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_print_array
    out.push_str("alya_print_array:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jnz .L_x86_arr_not_null\n");
    out.push_str("    push $alya_fmt_arr_empty\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    jmp .L_x86_arr_exit\n");
    out.push_str(".L_x86_arr_not_null:\n");
    out.push_str("    mov (%esi), %edi\n");
    out.push_str("    push $alya_fmt_arr_open\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_arr_loop:\n");
    out.push_str("    cmp %edi, %ebx\n");
    out.push_str("    jge .L_x86_arr_close_call\n");
    out.push_str("    test %ebx, %ebx\n");
    out.push_str("    jz .L_x86_arr_print_elem\n");
    out.push_str("    push $alya_fmt_arr_comma\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_arr_print_elem:\n");
    out.push_str("    mov 8(%esi), %edx\n");
    out.push_str("    push (%edx, %ebx, 4)\n");
    out.push_str("    push $alya_fmt_arr_elem\n");
    out.push_str("    call printf\n");
    out.push_str("    add $8, %esp\n");
    out.push_str("    inc %ebx\n");
    out.push_str("    jmp .L_x86_arr_loop\n");
    out.push_str(".L_x86_arr_close_call:\n");
    out.push_str("    push $alya_fmt_arr_close\n");
    out.push_str("    call printf\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_arr_exit:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_args
    out.push_str(".global fn_args\n");
    out.push_str("fn_args:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov alya_argc, %eax\n");
    out.push_str("    cmp $1, %eax\n");
    out.push_str("    jg .L_x86_args_has_items\n");
    out.push_str("    push $0\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    jmp .L_x86_args_ret\n");
    out.push_str(".L_x86_args_has_items:\n");
    out.push_str("    dec %eax\n");
    out.push_str("    mov %eax, %esi\n");
    out.push_str("    push %esi\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov %eax, %edi\n");
    out.push_str("    mov alya_argv, %edx\n");
    out.push_str("    xor %ecx, %ecx\n");
    out.push_str(".L_x86_args_loop:\n");
    out.push_str("    cmp %esi, %ecx\n");
    out.push_str("    jge .L_x86_args_done\n");
    out.push_str("    mov 4(%edx, %ecx, 4), %eax\n");
    out.push_str("    mov 8(%edi), %ebx\n");
    out.push_str("    mov %eax, (%ebx, %ecx, 4)\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    jmp .L_x86_args_loop\n");
    out.push_str(".L_x86_args_done:\n");
    out.push_str("    mov %edi, %eax\n");
    out.push_str(".L_x86_args_ret:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // alya_array_slice(arr, start, end)
    out.push_str(".global alya_array_slice\n");
    out.push_str("alya_array_slice:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    push %ebx\n");
    out.push_str("    push %esi\n");
    out.push_str("    push %edi\n");
    out.push_str("    mov 8(%ebp), %esi\n");
    out.push_str("    mov 12(%ebp), %ebx\n");
    out.push_str("    mov 16(%ebp), %edi\n");
    out.push_str("    test %esi, %esi\n");
    out.push_str("    jz .L_x86_slice_empty\n");
    out.push_str("    mov (%esi), %edx\n");
    out.push_str("    cmp $0, %ebx\n");
    out.push_str("    jge .L_x86_slice_start_ok\n");
    out.push_str("    xor %ebx, %ebx\n");
    out.push_str(".L_x86_slice_start_ok:\n");
    out.push_str("    cmp $0, %edi\n");
    out.push_str("    jl .L_x86_slice_end_cap\n");
    out.push_str("    cmp %edx, %edi\n");
    out.push_str("    jle .L_x86_slice_end_ok\n");
    out.push_str(".L_x86_slice_end_cap:\n");
    out.push_str("    mov %edx, %edi\n");
    out.push_str(".L_x86_slice_end_ok:\n");
    out.push_str("    cmp %edi, %ebx\n");
    out.push_str("    jge .L_x86_slice_empty\n");
    out.push_str("    mov %edi, %edx\n");
    out.push_str("    sub %ebx, %edx\n");
    out.push_str("    push %edx\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str("    mov %edi, %edx\n");
    out.push_str("    sub %ebx, %edx\n");
    out.push_str("    mov 8(%esi), %esi\n");
    out.push_str("    mov 8(%eax), %edi\n");
    out.push_str("    xor %ecx, %ecx\n");
    out.push_str(".L_x86_slice_copy_loop:\n");
    out.push_str("    cmp %edx, %ecx\n");
    out.push_str("    jge .L_x86_slice_copy_done\n");
    out.push_str("    lea (%ebx, %ecx), %r8d\n");
    out.push_str("    mov (%esi, %r8d, 4), %r9d\n");
    out.push_str("    mov %r9d, (%edi, %ecx, 4)\n");
    out.push_str("    inc %ecx\n");
    out.push_str("    jmp .L_x86_slice_copy_loop\n");
    out.push_str(".L_x86_slice_copy_done:\n");
    out.push_str("    mov %edx, (%eax)\n");
    out.push_str("    jmp .L_x86_slice_done\n");
    out.push_str(".L_x86_slice_empty:\n");
    out.push_str("    push $0\n");
    out.push_str("    call alya_array_new\n");
    out.push_str("    add $4, %esp\n");
    out.push_str(".L_x86_slice_done:\n");
    out.push_str("    pop %edi\n");
    out.push_str("    pop %esi\n");
    out.push_str("    pop %ebx\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");

    // fn_slice
    out.push_str(".global fn_slice\n");
    out.push_str("fn_slice:\n");
    out.push_str("    push %ebp\n");
    out.push_str("    mov %esp, %ebp\n");
    out.push_str("    mov 8(%ebp), %eax\n");
    out.push_str("    test %eax, %eax\n");
    out.push_str("    jz .L_x86_fn_slice_null\n");
    out.push_str("    mov -8(%eax), %edx\n");
    out.push_str("    cmp $0x5A110001, %edx\n");
    out.push_str("    jne .L_x86_fn_slice_str\n");
    out.push_str("    push 16(%ebp)\n");
    out.push_str("    push 12(%ebp)\n");
    out.push_str("    push %eax\n");
    out.push_str("    call alya_array_slice\n");
    out.push_str("    add $12, %esp\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n");
    out.push_str(".L_x86_fn_slice_str:\n");
    out.push_str("    mov 16(%ebp), %edx\n");
    out.push_str("    mov 12(%ebp), %ecx\n");
    out.push_str("    cmp $0, %edx\n");
    out.push_str("    jl .L_x86_fn_slice_str_call\n");
    out.push_str("    sub %ecx, %edx\n");
    out.push_str("    cmp $0, %edx\n");
    out.push_str("    jge .L_x86_fn_slice_str_call\n");
    out.push_str("    xor %edx, %edx\n");
    out.push_str(".L_x86_fn_slice_str_call:\n");
    out.push_str("    push %edx\n");
    out.push_str("    push %ecx\n");
    out.push_str("    push %eax\n");
    out.push_str("    call fn_substring\n");
    out.push_str("    add $12, %esp\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n");
    out.push_str(".L_x86_fn_slice_null:\n");
    out.push_str("    xor %eax, %eax\n");
    out.push_str("    mov %ebp, %esp\n");
    out.push_str("    pop %ebp\n");
    out.push_str("    ret\n\n");
}
